feat(date-block): Adding composition - FRONT-3320
openeuropa/bootstrap-component-library pull request #124
Opened 2021-11-05 14:31 UTC by planctus

2021-11-08 15:38 UTC, papegaill requested changes

2021-11-08 15:38 UTC, papegaill commented on src/compositions/bcl-date-block/date-block.story.js
> +Listing.storyName = "In a listing item";
wouldn't be better to have this under under Paragraphs/Listings as the others, 1, 2 and 3 columns ?

2021-11-08 16:04 UTC, theosuja commented on src/themes/default/src/scss/_variables.scss
>  $gray-100: #f0f0f0;
but then `light` would be darker than `gray-100`

2021-11-08 16:18 UTC, planctus commented
thanks for the review, @papegaill, i had a conversation with Romain and i turned out that they want a "kind of" fixed width for both the standard listing item image and this "date" variant, these adaptations have been performed in this pr, it seems the overall look and feel of the listings improved. I took care of the few points here, i kept the variable i added for the color for the moment, if it comes out from somewhere else we will adapt this. ;)

2021-11-08 16:25 UTC, theosuja commented on src/themes/default/src/scss/_variables.scss
>  $gray-100: #f0f0f0;
OK, looks like it is like that in Figma. 
So `$light: #f0f0f0` and `$gray-100: #f8f9fa`. But we need to sync and create a utility for "gray-100" backgrounds, because they are needed (and the names `bg-light` and `bg-gray` are already taken.

2021-11-09 07:56 UTC, planctus commented on src/themes/default/src/scss/_variables.scss
>  $gray-100: #f0f0f0;
guys, this discussion seems to me totally unrelated to this implementation. Whatever thing we need to do is not going to be done here, if the value of the bg-light will change we will just need to "fix" the card background as a follow up action of this change/fix in the variables.

2021-11-09 08:34 UTC, papegaill requested changes

2021-11-09 08:34 UTC, papegaill commented on src/compositions/bcl-date-block/date-block.html.twig
> +  'm-auto',
`m-auto` does not seem necessary for the composition as well as the listing

2021-11-09 08:34 UTC, papegaill commented on src/compositions/bcl-date-block/date-block.html.twig
> +  <span class="bg-light w-100 text-center py-2 text-dark">{{ _year }}</span>
bottom rounded border missing

2021-11-09 08:34 UTC, papegaill commented on src/compositions/bcl-date-block/date-block.story.js
> +      defaultViewport: "mobile1",
since we have a max-width, it may no longer be necessary to use the mobile viewport here?

2021-11-09 09:53 UTC, planctus commented on src/compositions/bcl-date-block/date-block.story.js
> +      defaultViewport: "mobile1",
i don't know why you are so against choosing a default display, honestly, but fine for me, i will demo it in "responsive".. :)

2021-11-09 10:07 UTC, planctus commented on src/compositions/bcl-date-block/date-block.html.twig
> +  <span class="bg-light w-100 text-center py-2 text-dark">{{ _year }}</span>
wow, not a fan of rounded corners, didn't foresee the issue we were running into, the solution was not as straightforward as i would have imagined... :)

2021-11-09 12:31 UTC, papegaill approved these changes

2021-11-09 13:43 UTC, emeryro commented
looks good for me :heavy_check_mark:

2021-11-09 14:23 UTC, merged