feat(listing): Listing on all compositions - FRONT-3357
openeuropa/bootstrap-component-library pull request #125
Opened 2021-11-08 07:35 UTC by tibi2303

2021-11-09 16:23 UTC, theosuja approved these changes

2021-11-10 13:53 UTC, tibi2303 commented on src/compositions/bcl-listing/listing.html.twig
> +{% set _responsive_vertical_spacer = responsive_vertical_spacer|default('') %}
This is mostly used for the case when the image is hidden on mobile.

2021-11-10 13:55 UTC, planctus requested changes
I don't know what kind of changes i'#m requesting, the truth is that it seems to me that the listing needs to be tweaked regarding all the things you altered thanks to an additional parameter, the idea is that the listing should work out of the box, zero configuration (well, the variant..), the alignment is the only one that maybe we need to keep but i believe we could get rid of the others...

2021-11-10 13:55 UTC, planctus commented on src/compositions/bcl-listing/listing.html.twig
> +          left_col_classes: 'col-md-3 col-lg-2 rounded ' ~ _max_width ~ (_alignment ? ' align-self-' ~ _alignment : ''),
well, ok...could we just improve a bit the syntax, like define this class in the upper part of the template together with the other processing of the user data and then use a short ternary operator `?:` here...

2021-11-10 13:55 UTC, planctus commented on src/compositions/bcl-listing/listing.html.twig
> +      {% if not _remove_horizontal_spacer %}
i believe we should investigate the usage of this utility, the reason for it, more than using a parameter to avoid it.
I did not even remember about this class added in the default , when i saw it i was suprised..

2021-11-10 13:55 UTC, planctus commented on src/compositions/bcl-listing/listing.html.twig
> +        'mb-' ~ _responsive_vertical_spacer ~ '2',
mmh..also this margin-bottom surprised me when i saw it..do we need it, responsive or not..?

2021-11-10 13:56 UTC, planctus commented on src/compositions/bcl-listing/listing.html.twig
> +{% set _responsive_vertical_spacer = responsive_vertical_spacer|default('') %}
do we have such a use case..? :)

2021-11-10 13:58 UTC, tibi2303 commented on src/compositions/bcl-listing/listing.html.twig
> +  - responsive_vertical_spacer: (string) (default: '') options:
I really tried to find another way, this is used when the image is hidden on mobile, the spacing top is too big. Somehow i need to find out if the image is hidden on mobile.
![image](https://user-images.githubusercontent.com/36895476/141126199-93d1b668-e3db-41d1-a4e1-1ab2eefd0b28.png)

2021-11-10 13:59 UTC, tibi2303 commented on src/compositions/bcl-listing/listing.html.twig
> +{% set _responsive_vertical_spacer = responsive_vertical_spacer|default('') %}
https://preview-125--oelibrary.netlify.app/default/?path=/story/compositions-group-listing--list

2021-11-10 14:33 UTC, tibi2303 commented on src/compositions/bcl-listing/listing.html.twig
> +      {% if not _remove_horizontal_spacer %}
here is the figma:
![image](https://user-images.githubusercontent.com/36895476/141127143-897ab967-4972-4d0c-9fe4-763e078a7f25.png)

2021-11-11 08:53 UTC, planctus commented on src/compositions/bcl-listing/listing.html.twig
> +        alt: _card.image.alt ?: "",
mmhh...i don't get this approach, we have an object with the same keys, why do we "rebuild it"..? I understand you want to set a class  why don't you do it with a |merge..?

2021-11-11 08:57 UTC, planctus reviewed
a few inline comments left

2021-11-11 08:57 UTC, planctus commented on src/compositions/bcl-listing/listing.html.twig
> +  attributes: create_attribute().addClass(['gy-4']),
maybe we can leave this as it was since no one complained about it.. :)

2021-11-11 08:57 UTC, planctus commented on src/compositions/bcl-listing/listing.html.twig
> +        extra_classes_body: 'p-0 pb-md-0 pb-3',
this is problematic:
![image](https://user-images.githubusercontent.com/14326885/141268097-5cf9b0d7-5518-4220-bcde-b9aee798f4ff.png)

2021-11-11 09:55 UTC, tibi2303 commented on src/compositions/bcl-listing/listing.html.twig
> +        extra_classes_body: 'p-0 pb-md-0 pb-3',
We should be good now, i missed to add it to the 2 and 3 variants

2021-11-11 09:55 UTC, tibi2303 commented on src/compositions/bcl-listing/listing.html.twig
> +  attributes: create_attribute().addClass(['gy-4']),
with 4-5 has the same spacing top and bot

2021-11-11 09:55 UTC, tibi2303 commented on src/compositions/bcl-listing/listing.html.twig
> +        alt: _card.image.alt ?: "",
Done. thanks for the help.

2021-11-11 12:31 UTC, planctus approved these changes

2021-11-11 14:53 UTC, planctus approved these changes

2021-11-11 15:07 UTC, merged