fix(gray-palette): Avoid $gray-100 override assigning specific color to light btn and badge. - FRONT-3363
openeuropa/bootstrap-component-library pull request #126
Opened 2021-11-08 14:33 UTC by theosuja

Feel free to share different points of view on how to fix this.

2021-11-08 15:48 UTC, papegaill reviewed
Not that easy to understand the history here of these light gray colors changes...
to me the light color should be #F0F0F0 as on figma default palette colors and gray-100 #F8F9FA
 
please see my remarks on following PR: https://github.com/openeuropa/bootstrap-component-library/pull/124#discussion_r744841537

2021-11-09 08:24 UTC, planctus commented on src/themes/default/src/scss/_buttons.scss
> +.btn-light {
I don't understand, really...We have a color palette, then we have this "semantic" colors, like "light", "dark".
This color you are adding shouldn't be now the value of the $light variable and all the utilities generated out of this variable would use it..?
Why overriding the "light" for badges and buttons specifically, instead? The idea is really bad per se, this is a generated utility and we override the selector, not the parameters that generate it...

2021-11-09 08:29 UTC, theosuja commented on src/themes/default/src/scss/_buttons.scss
> +.btn-light {
Again: according to the designs we need sometimes elements with a gray `#f0f0f0` background and some other elements with a gray `#f8f9fa` background. From the dev side, we are handling both with the same approach: adding `bg-light` utility. 
- Either we force designers to merge both grays into only one
- Either we use different utility classes, like `bg-light`, `bg-gray` (both already existing) and ` bg-lightgray` or whatever you prefer
- Either we override only the components that are problematic that's what i pretended to do

2021-11-09 12:27 UTC, planctus requested changes
Cool, i haven't checked myself all the use cases of this bg-light we had, but now it makes sense, just we don't need all those classes generated out of the theme colors, let's just add bg-lighter

2021-11-09 12:27 UTC, planctus commented on src/themes/default/src/scss/_variables.scss
> +$light: #f0f0f0; // Make light btns and badges background darker
would you remove these comments..? i don't find them useful.

2021-11-09 12:27 UTC, planctus commented on src/themes/default/src/scss/_variables.scss
>  $theme-colors: map-merge(
you know what..? I told you to add this as a theme color, but there are so many selectors created this way and in the end we only need the background utility, not more than that.
So maybe you can remove this merge with the theme colors map, then you keep the rest of the code under the comment "add color lighter to bg utilities" so that we only have this new class available.

2021-11-09 12:27 UTC, planctus commented on src/themes/default/src/scss/_variables.scss
> +// Add color "lighter" to bg utilities
There is an "utility.scss" file now in the default theme, this should go there, you can also check the "date" pr, there i moved everything related to utilities in this file.

2021-11-09 12:40 UTC, theosuja commented on src/themes/default/src/scss/_variables.scss
> +// Add color "lighter" to bg utilities
sure!

2021-11-09 12:42 UTC, theosuja commented on src/themes/default/src/scss/_variables.scss
>  $theme-colors: map-merge(
I tried to only add it to the background utility map, but it looks like the class `bg-lighter` needs the `light` pair to be inside `theme-colors`... otherwise, the `bg-lighter` is `background-color: --bs-lighter-rgb` which is undefined

2021-11-09 13:10 UTC, planctus commented
please take also care of the title of this pull request, it will go in the changelog, here we are adding one utlity class, basically, this should be in the title, and something like feat(utlities)

2021-11-09 13:10 UTC, planctus commented on src/themes/default/src/scss/_variables.scss
>  $theme-colors: map-merge(
too bad, i haven't tested this...uff

2021-11-09 14:22 UTC, planctus commented on src/themes/default/src/scss/_variables.scss
>  $theme-colors: map-merge(
well, i know this will sound silly...but really we don't need these amount of selectors, let's do it dirty, create this `bg-lighter` selector manually in `_utilities.scss` and that's going to be enough..you can protest, eh.. :)

2021-11-09 14:40 UTC, theosuja commented on src/themes/default/src/scss/_variables.scss
>  $theme-colors: map-merge(
go for the silly approach!
It's not silly, it's realistic. I also thought about doing it that way at some point, but I was not sure it would be accepted

2021-11-09 15:39 UTC, planctus commented on src/themes/default/src/scss/_utilities.scss
> +$theme-colors: map-merge(
sorry..this should go back to the variables file, this is not about utilities, it's a map of colors that we are altering.

2021-11-09 15:43 UTC, planctus requested changes
Cool, that's it, move this code and we merge this.. ;)

2021-11-09 15:43 UTC, planctus commented on src/compositions/bcl-listing/listing.html.twig
> +        'bg-lighter',
thanks, you checked again, this was just merged.. ;)

2021-11-09 15:49 UTC, theosuja commented on src/themes/default/src/scss/_utilities.scss
> +$theme-colors: map-merge(
ok, my bad!

2021-11-10 08:56 UTC, planctus approved these changes

2021-11-10 08:56 UTC, merged