feat(file): Added file paragraph. - Front 3139
openeuropa/bootstrap-component-library pull request #132
Opened 2021-11-15 13:37 UTC by tibi2303

2021-11-16 11:57 UTC, planctus requested changes
Not sure i looked at everything, we miss the dependency in bcl-twig-templates, eh.. ;)

2021-11-16 11:57 UTC, planctus commented on src/compositions/bcl-file/file.html.twig
> +  - file (string) (default: '')
it's not a string, but maybe it should...in ECL it's like that, the param name is "meta", i don't think we need an object, "language" is a param in the root of the component, let's not change these things...

2021-11-16 11:57 UTC, planctus commented on src/compositions/bcl-file/file.html.twig
> +    <div class="text-{{ _other_dropdown.alignment }}">
do we need to know the alignment from the data..? I mean, does it need to be parametric..?

2021-11-16 11:57 UTC, planctus commented on src/compositions/bcl-file/file.html.twig
> +    {% include '@oe-bcl/bcl-link/link.html.twig' with _other_dropdown.dropdown_label|merge({
You really like verbose data, i asked you to rename `other_dropdown` but then did you need to set the label as `dropdown_label`, couldn't it just be `label`

2021-11-16 11:57 UTC, planctus commented on src/compositions/bcl-file/file.html.twig
> +      path: "#" ~ _other_dropdown.id,
i think we shouldn't ask for `ids` in the data, if we need an id to be set i believe we can define it ourselves with a `random(max)`

2021-11-16 18:56 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +    {% include '@oe-bcl/bcl-link/link.html.twig' with _other_dropdown.dropdown_label|merge({
Yes, on figma is either on center or the right.

2021-11-16 18:56 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +    <div class="text-{{ _other_dropdown.alignment }}">
alignment

2021-11-16 20:36 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +{% set _card = card|default({}) %}
I am not sure if understood corectly (to add all data for the card at root level of componenent and also make the markup without using the card component) but why overcomplicate stuff... I made the data easier for the user to add it, the grid and the image classes are set by default now.

2021-11-16 20:36 UTC, tibi2303 commented on src/compositions/bcl-file/file.story.js
> +export const Default = () => file(correctPaths(demoData));
Done, it's for the download link to go under the title and meta of item, not at the end of block.

2021-11-16 20:36 UTC, tibi2303 commented on src/compositions/bcl-file/file.story.js
> +export const Default = () => file(correctPaths(demoData));
This variant exists in figma.

2021-11-16 20:36 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +{% set _other_dropdown = other_dropdown|default({}) %}
Done.

2021-11-16 20:37 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +{% set _inline_download = inline_download|default(true) %}
It's for the download link to go under the title and meta of item, not at the end of block. I dont think we need a variant here, only a simple boolean.
This variant exists in figma.

2021-11-16 20:38 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +  {% set attributes = attributes.addClass(["border-start", "border-end", "border-top", "rounded-bottom"]) %}
Indeed, i changed this... :(

2021-11-16 20:38 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +            {{ _file.language }}
I made it the same as on ecl now.

2021-11-16 20:38 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +  - file (string) (default: '')
Same as on ecl now.

2021-11-16 20:39 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +    {% include '@oe-bcl/bcl-link/link.html.twig' with _other_dropdown.dropdown_label|merge({
Done.

2021-11-16 20:39 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +      path: "#" ~ _other_dropdown.id,
The tests fail if it's hardcoded by default. I also add the possibility for the user to add but still generate it by default.

2021-11-18 13:15 UTC, planctus commented on src/compositions/bcl-file/file.html.twig
> +{% set _inline_download = inline_download|default(true) %}
i actually believe this is just the way the download link would be in mobile, or when there is no space..i don't see the reason why the user would choose one or the other, doesn't make much sense, could you verifiy with the designers..?

2021-11-18 13:20 UTC, planctus commented on src/compositions/bcl-file/file.html.twig
> +    <div class="text-{{ _other_dropdown.alignment }}">
mmh...i see it on the right only in mobile, why would the user choose between the two, it cannot be..

2021-11-18 13:23 UTC, planctus commented on src/compositions/bcl-file/file.html.twig
> +{% set _card = card|default({}) %}
So...the concept is basically this: i'm implementing this template and i have my set of data for it, i don't see the reason why, if i want the "card" variant then i have to change my data in order to have it as a card object, what should happen is instead that in our template, if the variant is card we build a card object ourselves and we pass it to the card, but it should be transparent for the user, he is not implementing the card, but the file download.

2021-11-18 13:24 UTC, planctus commented
the npmignore is missing

2021-11-18 15:49 UTC, merged