feat(description-list): Added description list - FRONT-2562
openeuropa/bootstrap-component-library pull request #133
Opened 2021-11-16 11:14 UTC by tibi2303

2021-11-16 12:05 UTC, planctus requested changes
I think there was a misunderstanding here :)

2021-11-16 12:05 UTC, planctus commented on src/compositions/bcl-description-list/description-list.html.twig
> +{#
i'm confused, this is called description list but this is actually a template for a single item thingy with a label and a value...
This template should be used to produce a list, and the description list i guess it refers to the html description list:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

2021-11-16 12:05 UTC, planctus commented on src/compositions/bcl-description-list/description-list.html.twig
> +    {{- _label -}}
wouldn't it be better not to expect any markup from the user data..? couldn't we get just the "text" content..?

2021-11-16 12:09 UTC, planctus commented
You keep forgetting to add the component/compositions you add as a dependency in bcl-twig-templates...

2021-11-17 11:43 UTC, tibi2303 commented on src/compositions/bcl-description-list/description-list.html.twig
> +{#
Remade it the way on ecl, not sure about the extra markup for horizontal though..

2021-11-17 11:43 UTC, tibi2303 commented on src/compositions/bcl-description-list/description-list.html.twig
> +    {{- _label -}}
changed it

2021-11-18 12:25 UTC, planctus approved these changes

2021-11-18 14:23 UTC, merged