feat(outline-badges): Added outline badges and modified listing data. - FRONT-3429
openeuropa/bootstrap-component-library pull request #152
Opened 2021-11-30 10:17 UTC by tibi2303

2021-12-02 08:33 UTC, planctus requested changes
I think you forgot some data file, like the content banner ones maybe, please double check this..

2021-12-02 08:33 UTC, planctus commented on src/components/bcl-badge/badge.html.twig
>  {% set _rounded_pill = rounded_pill|default(false) %}
question:
couldn't we introduce the variant parameter..? We now have default, pill and outline, i feel this would be the way to handle this. But this would introduce a breaking change, at least because if the rounded_pill parameter is "used" in the drupal paragraph. We can anticipate this to the developers and see if they can handle this in the next release.

2021-12-02 08:33 UTC, planctus commented on src/themes/default/src/scss/_badge.scss
> +@each $color, $value in $theme-colors {
mmh..this is not enough, if you check the styles the "circle" has the same background color of the border, the x can be white or kind of black...

2021-12-02 09:49 UTC, papegaill requested changes
Thanks 👍  here is a few small remarks for the users profile pages.

**Listing:**
<img width="353" alt="Screenshot 2021-12-02 at 10 27 13" src="https://user-images.githubusercontent.com/1289480/144397431-af4f1903-8439-4182-824e-1f8e524a900d.png">
missing little space above the pagination

**Edit:**
<img width="236" alt="Screenshot 2021-12-02 at 10 27 39" src="https://user-images.githubusercontent.com/1289480/144397652-09fe60a5-0975-4204-b6e5-b1079475f6c6.png">
should  be light gray

<img width="119" alt="Screenshot 2021-12-02 at 10 27 48" src="https://user-images.githubusercontent.com/1289480/144397804-3b7c92ac-a4ba-4b7c-8f43-567289f93caa.png">
missing space bellow the button

**View:**
<img width="251" alt="Screenshot 2021-12-02 at 10 27 59" src="https://user-images.githubusercontent.com/1289480/144397971-8d5581e8-14d0-4431-a4e2-701f48a4d4bb.png">
should  be light gray

<img width="1056" alt="Screenshot 2021-12-02 at 10 28 15" src="https://user-images.githubusercontent.com/1289480/144398070-e0732cbd-aeeb-4861-8818-a245dfec9458.png">
missing space bellow the content

2021-12-02 16:03 UTC, planctus requested changes
I still see the normal badges used  in many stories, think i've asked to double check previously, i believe it should be easy, considering that everyhwere i see badges in figma they are pills and with the outline...

2021-12-03 11:48 UTC, planctus reviewed
can we add some margin of the default card story..?
Actually we could also remove the button there, it looks bad there together with badges..

2021-12-06 08:03 UTC, tibi2303 commented
Done @planctus

2021-12-06 08:48 UTC, planctus approved these changes

2021-12-06 08:49 UTC, merged