feat(multilingual): Added feature - OEL-1084
openeuropa/bootstrap-component-library pull request #245
Opened 2022-02-01 11:45 UTC by tibi2303

2022-02-03 09:38 UTC, planctus commented on src/components/bcl-twig-templates/package.json
> +    "@openeuropa/bcl-language": "^0.19.0",
i don't understand the naming. i would name the "main" package as the feature is: bcl-multilingual and its story should be in the Features group for consistency. This demo for me should show a standard page with the language list modal opened, like if the user clicked already on the language switcher button.

I would then separate the "story" from the twig package, i mean that bcl-multilingual could basically only contain the story and the needed data, not even being a public package, and i would have a **language-list** composition with templates named:
**language-list.html.twig**
**language-list-overlay.html.twig**

In ECL there is a template for the item that is called from the main template, but i don't think we need to reproduce that, but i would expected this template to be based a bit more (when possible) on the data structure of the ECL component including the parameters name.
Did you take into account the ECL version of this "feature"..? Because surely this exists already in drupal, using that template, so the more we limit the changes the best is, i think..

2022-02-04 15:26 UTC, planctus requested changes
Small things, thanks a lot for this work, this is a big pull request, it seems fine to me now.. ;)

2022-02-04 15:26 UTC, planctus commented on src/compositions/bcl-language-list/language-list-modal.html.twig
> +    attributes: create_attribute()
mmh...why this? To reset them..? But these attributes once sent back to the language-list template would not be used, right? so it doesn't look like we need this..

2022-02-04 15:26 UTC, planctus commented on src/compositions/bcl-language-list/language-list-modal.html.twig
> +        name: "globe",
single quotes

2022-02-04 15:26 UTC, planctus commented on src/compositions/bcl-language-list/language-list.html.twig
> +
one empty line is enough.. :)

2022-02-04 15:26 UTC, planctus commented on src/compositions/bcl-language-list/language-list.story.js
> +  parameters: {
we don't have controls, can we disable the panel then..?

2022-02-04 15:26 UTC, planctus commented on src/compositions/bcl-language-list/language-list.test.js
> +  });
shouldn't we add a test also for the modal.?

2022-02-06 14:24 UTC, tibi2303 commented on src/compositions/bcl-language-list/language-list-modal.html.twig
> +    attributes: create_attribute()
![image](https://user-images.githubusercontent.com/36895476/152685436-b6981e56-cb74-4259-a000-866873745026.png)
They are being used after the base template it's called and also i need to reset them in order to clear the classes i put on the modal here:
![image](https://user-images.githubusercontent.com/36895476/152685461-ba2fcf71-23b3-4884-a5ec-edaa317735c7.png)

2022-02-06 14:27 UTC, tibi2303 commented on src/compositions/bcl-multilingual/.npmignore
> +*.js
done.

2022-02-06 14:27 UTC, tibi2303 commented on src/compositions/bcl-language-list/language-list.html.twig
> +  - icon_path (string) (default: '')
done.
I will create a ticket regarding this, i think we should change all of them into 'icon_path'

2022-02-06 14:27 UTC, tibi2303 commented on src/compositions/bcl-language-list/language-list.html.twig
> +{% set _id = id|default('') %}
yes, thank you. I deleted it.

2022-02-06 14:28 UTC, tibi2303 commented on src/compositions/bcl-language-list/language-list-modal.html.twig
> +        name: "globe",
done.

2022-02-06 14:28 UTC, tibi2303 commented on src/compositions/bcl-language-list/language-list.html.twig
> +
done.

2022-02-06 14:28 UTC, tibi2303 commented on src/compositions/bcl-language-list/language-list.story.js
> +  parameters: {
done. Also disabled them in Multilingual too

2022-02-06 14:28 UTC, tibi2303 commented on src/compositions/bcl-language-list/language-list.test.js
> +  });
They are already tested in header but i added in here too for each variant.

2022-02-07 08:31 UTC, planctus approved these changes

2022-02-07 08:41 UTC, merged