feat(project): Add circular progress bar for project status - OEL-1137
openeuropa/bootstrap-component-library pull request #255
Opened 2022-02-08 08:51 UTC by papegaill

2022-02-09 12:38 UTC, tibi2303 commented on src/compositions/bcl-project-status/project-status.html.twig
> +  <div class="row">
As we talked i think it would be better to have this behaviour in the progress component. I know it can be a bit tricky, but i find this to be only a variant to that component.

2022-02-09 12:39 UTC, tibi2303 commented on src/themes/default/src/scss/_circular-progress-bar.scss
> +  font-size: 36px;
This can be added as variables, or even use the bs variables.

2022-02-09 12:39 UTC, tibi2303 requested changes
You can find some points I added here.

2022-02-09 12:40 UTC, tibi2303 commented on src/themes/default/src/scss/_circular-progress-bar.scss
> +  font-size: 36px;
I am reffering to all hardcoded values.

2022-02-10 08:39 UTC, planctus commented on src/compositions/bcl-project-status/project-status.html.twig
> +  <div class="row">
ideally this could be indeed a "variant" of the progress bootstrap component, but i don't think we need it as such, extending a bs component. We just have this use case here and it's probably better to keep it like this.
What i believe is that this project-status deserves now a story to be added, where we can also "expose" the relevant controls. ;)

2022-02-10 08:39 UTC, planctus commented on src/themes/default/src/scss/_circular-progress-bar.scss
> +  font-size: 36px;
so let's remove it.. :)

2022-02-10 08:54 UTC, planctus requested changes
It's cool, i think we can demo this "template" in the compositions, now.. ;)

2022-02-10 08:54 UTC, planctus commented on src/themes/default/src/scss/_circular-progress-bar.scss
> +  font-size: 36px;
so let's remove it.. :)

2022-02-10 08:54 UTC, planctus commented on src/themes/default/src/scss/_circular-progress-bar.scss
> +      -webkit-transform: rotate(0deg);
also this should not be needed

2022-02-10 08:54 UTC, planctus commented on src/themes/default/src/scss/oe-bcl-default.scss
> +@import "@openeuropa/bcl-theme-default/src/scss/circular-progress-bar";
we are not adding this to the sub-themes..?

2022-02-10 08:54 UTC, planctus commented on src/themes/default/src/scss/_circular-progress-bar.scss
> +      -webkit-transform: rotate($degrees);
same..but let's check the compiled css after removing it..

2022-02-10 08:54 UTC, planctus commented on src/compositions/bcl-project-status/project-status.html.twig
> +{% set _chart_progress = chart_progress|default('') %}
maybe this parameter could be renamed..? I see that technically. let's say, it's a progress value, but we use it as something different, something like "corporate_contribution"..? :)

2022-02-10 08:54 UTC, planctus commented on src/compositions/bcl-project-status/project-status.html.twig
> +{% set _chart_details_list = chart_details_list|default({}) %}
and this something like `chart_legend`..?

2022-02-11 08:34 UTC, papegaill commented on src/themes/default/src/scss/_circular-progress-bar.scss
> +      -webkit-transform: rotate($degrees);
there after compilation 👍

2022-02-11 10:17 UTC, papegaill commented on src/compositions/bcl-project-status/project-status.html.twig
> +  <div class="row">
done

2022-02-14 08:06 UTC, tibi2303 commented on src/compositions/bcl-project-status/project-status.story.js
> +  title: "Features/Project",
Please move it to compositions.

2022-02-14 08:15 UTC, tibi2303 commented on src/themes/default/src/scss/_circular-progress-bar.scss
> +.circular-progress-left {
Can you do it the same as on line 59?

2022-02-14 08:16 UTC, tibi2303 requested changes
2 small comments, then i think it can be accepted.

2022-02-16 13:38 UTC, closed without merging