feat(subscription): Added subscription page and modal - OEL-1121
openeuropa/bootstrap-component-library pull request #256
Opened 2022-02-08 15:10 UTC by tibi2303

2022-02-08 16:57 UTC, papegaill requested changes
Well done 👍  I don't really know how the backends will deal with validation, but I imagine that they will find a compromise between JS or Drupal validation on their side. Maybe, we will need to help them on this point.

Looking at the figma, i think there is a missing **subscribe** button in the `bcl-content-banner`.  Not certain that the **print** button should also be included in this feature?

2022-02-08 16:57 UTC, papegaill commented on src/compositions/bcl-subscription/subscription.story.js
> +  parameters: {
probably better to put the story in fullscreen like the other features
```suggestion
  parameters: { 
    layout: "fullscreen",
```

2022-02-08 16:57 UTC, papegaill commented on src/compositions/bcl-subscription/subscription-block.html.twig
> +  <h2 class="fw-normal">{{ _title }}</h2>
not sure a `<h2>` tag is needed here, not relevant for SEO. 
```suggestion
  <div class="fs-2 fw-normal">{{ _title }}</div>
```

2022-02-08 16:57 UTC, papegaill commented on src/compositions/bcl-subscription/subscription-modal.html.twig
> +  ]
`]` can be removed, and maybe specify here the 2 Blocks?
```suggestion
  Blocks:
  - body
  - outer_body
```

2022-02-09 12:33 UTC, tibi2303 commented on src/compositions/bcl-subscription/subscription.story.js
> +  parameters: {
done.

2022-02-09 12:33 UTC, tibi2303 commented on src/compositions/bcl-subscription/subscription-block.html.twig
> +  <h2 class="fw-normal">{{ _title }}</h2>
done.

2022-02-09 12:33 UTC, tibi2303 commented on src/compositions/bcl-subscription/subscription-modal.html.twig
> +  ]
done. but i guess it can be seen in modal too, it extends it.

2022-02-09 14:36 UTC, papegaill requested changes

2022-02-09 15:11 UTC, tibi2303 commented on src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
> +            class="d-flex justify-content-end"
We need to update the content_banner fully

2022-02-09 16:40 UTC, papegaill approved these changes

2022-02-10 09:52 UTC, planctus commented on src/compositions/bcl-subscription/subscription.story.js
> +import sidebar from "@openeuropa/bcl-inpage-navigation/data--simple";
but with this "data" we don't get a working inpage-navigation in this story...

2022-02-10 10:25 UTC, tibi2303 commented on src/compositions/bcl-subscription/subscription.story.js
> +import sidebar from "@openeuropa/bcl-inpage-navigation/data--simple";
Done and also I updated the sidebars in Page composition too and deleted some unnecessary imports on news.

2022-02-10 11:49 UTC, planctus commented on src/compositions/bcl-subscription/subscription-block.html.twig
> +{% spaceless %}
i like the fact that you created a template for this, it could be potentially used, but i would like the modal inclusion not to be part of this template. Is it going to complicate things..? I also think we should expose these templates we are using in the features, i think you can add a package, with a story for this in compositions.

2022-02-10 11:53 UTC, planctus commented on src/components/bcl-modal/modal.html.twig
> +      {%- block outer_body _outer_body -%}
not sure about the name for this...i agree in adding this "region" in the modal template, but to me that space is really only for alerts, so i would name this block "messages"...

2022-02-10 11:56 UTC, tibi2303 commented on src/compositions/bcl-subscription/subscription-block.html.twig
> +{% spaceless %}
That was i did on the first commit.. then i changed it.. don't really know why :D I will redo it now

2022-02-10 11:58 UTC, planctus reviewed
Few small things, the demos are really good (can you  disable the controls there.?)

2022-02-10 15:16 UTC, merged