feat(carousel): Carousel update - OEL-1197
openeuropa/bootstrap-component-library pull request #273
Opened 2022-02-23 12:43 UTC by tibi2303

2022-03-04 14:26 UTC, planctus commented on src/components/bcl-carousel/carousel.story.js
> +        category: "Behaviour",
we have a style category, i think this should be placed there

2022-03-04 14:27 UTC, planctus commented on src/components/bcl-carousel/carousel.html.twig
> +{% set _rounded_indicators = rounded_indicators|default(false) %}
is this an opt-in thingy, is not the default or the "only" available style of the bcl carousel..? In case it is just close this conversation ;)

2022-03-07 16:04 UTC, papegaill requested changes
the dark version of the carousel does not work correctly at the level of styles, caption and indicator don't become negative
<img width="831" alt="Screenshot 2022-03-07 at 17 00 19" src="https://user-images.githubusercontent.com/1289480/157070812-fbf58211-7456-41e4-af61-8240bdfeb44d.png">

2022-03-08 11:16 UTC, tibi2303 commented on src/components/bcl-carousel/carousel.html.twig
> +{% set _rounded_indicators = rounded_indicators|default(false) %}
default is squared, if you want rounded you set to true

2022-03-08 15:41 UTC, tibi2303 commented on src/components/bcl-carousel/carousel.html.twig
>  {% set _with_indicators = with_indicators|default(false) %}
![image](https://user-images.githubusercontent.com/36895476/157272109-3f852bfa-c7b7-4ae1-8240-252c6d0420a3.png)
![image](https://user-images.githubusercontent.com/36895476/157272138-960f4ffa-8942-4842-8ea5-8037ad8027f3.png)
![image](https://user-images.githubusercontent.com/36895476/157272211-b2e3b7bc-1e53-48c4-a90a-25167c805c58.png)

2022-03-08 15:42 UTC, tibi2303 commented on src/components/bcl-carousel/carousel.html.twig
>  {% set _with_indicators = with_indicators|default(false) %}
it should be good now, thx for feedback

2022-03-09 07:58 UTC, papegaill approved these changes

2022-03-09 08:35 UTC, merged