feat(icons): Added custom icons to all themes - OEL-1222
openeuropa/bootstrap-component-library pull request #276
Opened 2022-02-28 13:07 UTC by tibi2303

2022-02-28 14:38 UTC, planctus commented on src/themes/default/bcl-builder.config.js
> +        file: "bootstrap-icons.svg",
still thinking about this file name... The script is generating a "bcl-icons.svg" if you don't pass the file name, i think it's better, the bootstrap-icons.svg will stay as an available version provided by bs with all the icons, this sprite will be something namespaced, i see that in the example we use "bcl-default-icons.svg" and i think that in the end is the right name for it.
Now i understand that you will have to find and replace all the occurrencies of this file name but i think it's the right thing to do :)

2022-03-01 13:25 UTC, tibi2303 commented on src/themes/default/bcl-builder.config.js
> +        file: "bootstrap-icons.svg",
Done.

2022-03-04 14:09 UTC, planctus requested changes
Pretty good, a few things that can be improved, especially the "extension" of the bcl-bootstrap package including also all the svg sources of the icons.

2022-03-04 14:09 UTC, planctus commented on src/themes/default/bcl-builder.config.js
> +      entry: path.resolve(nodeModules, "bootstrap-icons/icons/"),
mmh..i don't like this, we wrap bootstrap everytime in our bcl-bootstrap package.
At the moment in that package we are only copying the sprite from bootstrap-icons, we can copy also all the svgs and then retrieve those from our package.

2022-03-04 14:09 UTC, planctus commented on src/themes/joinup/bcl-builder.config.js
> +const iconList = require("../default/src/icons/icons");
ahhh, no, why using a relative path, retrieve this from the package

2022-03-04 14:09 UTC, planctus commented on src/themes/ucpkn/bcl-builder.config.js
> +const iconList = require("../default/src/icons/icons");
same here, from the package

2022-03-04 14:09 UTC, planctus commented on tools/story-utils/index.js
>      "arrow-right",
it seems we removed many, maybe we can add some more in this filtered list..?

2022-03-07 11:25 UTC, planctus commented on .gitignore
> +bootstrap/icons/*.svg
you can write bootstrap/**/*.svg instead of line 11 and 12

2022-03-07 11:40 UTC, merged