FRONT-2599: Add path param to get a button as a link.
openeuropa/bootstrap-component-library pull request #28
Opened 2021-07-22 15:37 UTC by papegaill

2021-07-28 08:59 UTC, planctus requested changes

2021-07-28 08:59 UTC, planctus commented on src/components/bcl-link/link.html.twig
> +  - btn_styled (boolean) (default: false)
Mmhhh...i don't really think we should add these parameters to the link component, basically we use attributes for this reason, not to multiply the parameters in the template, here is a matter of passing certain attributes to it to get the desired result, which can be done without altering anything.

2021-07-28 08:59 UTC, planctus commented on src/components/bcl-link/link.html.twig
> +{% if _btn_styled %}
Beside the fact that this is unneeded for me, we could receive this already as attributes when you want to use a link and make it look like a button, here we do something strange, we add the class `btn`, then a class `btn-` which only in case there is an outline becomes` btn-outline- ` and only in case the variant is set it becomes an usable css class as `btn-outline-{variant}`. Then, separately, we add another class.
We don't have to use escaping while setting attributes values, they are already going to be escaped by the attributes method used.
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Template%21Attribute.php/class/Attribute/8.5.x

2021-07-28 08:59 UTC, planctus commented on src/components/bcl-link/link.story.js
> +    btn_styled: {
As said, to me these parameters are unneeded, but if you really want to keep them tests should be added for them, they would show the current inconsistencies.

2021-07-30 10:07 UTC, papegaill commented on src/components/bcl-link/link.html.twig
> +  - btn_styled (boolean) (default: false)
if you pass `variant` you will have the `link-variant` class, so to me it can be confusing to k ow how to generate a button link, only by passing attributes..

2021-07-30 10:10 UTC, papegaill commented on src/components/bcl-link/link.html.twig
> +{% if _btn_styled %}
I just took this part of the button component code..

2021-07-30 10:10 UTC, papegaill commented on src/components/bcl-link/link.html.twig
> +{% if _btn_styled %}
I just took this part of the button component code..

2021-07-30 10:12 UTC, papegaill commented on src/components/bcl-link/link.html.twig
> +  - btn_styled (boolean) (default: false)
So your idea would be to leave the component as is and probably put an explanation that to generate the style of a button you can pass the `btn`, `btn-..`, `btn-outline- ..` classes as attributes?

2021-07-30 13:29 UTC, planctus commented on src/components/bcl-link/link.html.twig
> +  - btn_styled (boolean) (default: false)
To me the opposite is confusing, both when we were thinking of altering the button template to output a link and now that we are adding button params to a link.
I would actually say that the idea of using a link that it looks like a button is confusing per se:
https://medium.com/simple-human/but-sometimes-links-look-like-buttons-and-buttons-look-like-links-9b371c57b3d2

Still the possibility is there, you can do it with the current template and it is just a matter of passing classes.
The idea that i have is that, to a certain extent, we should not have parameters anymore if they are only meant to add attributes, since we use the drupal attributes, but the agreement with the "drupal guys" was to leave things as they were, in the first phase, and then see if we could simplify the templates by removing some or all those params, so i just feel i don't want to increase their number, cause i actually feel we could go decreasing them in the future :)

2021-07-30 13:43 UTC, closed without merging