feat(project): Project details update - OEL-1237
openeuropa/bootstrap-component-library pull request #285
Opened 2022-03-03 14:15 UTC by tibi2303

2022-03-04 08:53 UTC, planctus requested changes
I'm not sure what all the changes in the project test are about, but i wouldn't expect changes there in the "default" test, i would have instead expected a separated test for ucpkn specifically.

2022-03-04 08:53 UTC, planctus commented on src/compositions/bcl-project/project.html.twig
> +  {% if project_status.main_title is not empty %}
i see that you decided to do this in a different way than the "recommended" one. I'm not really sure there is any value in extending a "feature" template at all, especially if this introduces a more complex data structure that is already overwhelming and if it results in changes about the markup of the other "themes". 
This would mean that the project would need to be updated also in the oe-bootstrap-theme while it seems to me that this could be avoided, regardless of the extension of the current project template or its override in the ucpk theme. 

I believe we should not distribute these templates, they are clearly only for an internal use, it's just confusing to have them in the distributed theme package, need to see how to do this.

2022-03-04 08:53 UTC, planctus commented on src/compositions/bcl-project/__snapshots__/project.test.js.snap
> +          Summary
it seems we introduced some wthitespaces issues here. But this test should not have any change in my opinion, we didn't have to touch the "project" demo for the default theme in any way. It seems to me that it contains changes that would need to be applied on the default project implementation in drupal, which was not foreseen and should be avoided.

2022-03-04 08:53 UTC, planctus commented on src/themes/ucpkn/src/data/project/data.js
> +const drupalAttribute = require("drupal-attribute");
Mmh..we never introduced a data folder in the themes, but i see that it makes probably sense in this case.
But we have to npmignore these files so that we don't ship them in the theme package, at the same time this is an issue because there is no package on npm containing the needed src files for the "package" feature to work on ucpkn. 

So, basically i think these data files should be released in a package and this package can either be:

-  a data package
-  data files contained in a "feature" package

I think it's still ok to ship these files in the "feature" npm package, but i would also be fine with the creation of a dedicated data package.

2022-03-04 08:53 UTC, planctus commented on src/themes/ucpkn/src/stories/project.story.js
> +const social_buttons = `
we have dozens of data files imported and then we have this directly defined in the story..? :)

2022-03-04 10:03 UTC, tibi2303 commented on src/themes/ucpkn/src/stories/project.story.js
> +const social_buttons = `
done. added directly into data file.

2022-03-04 10:03 UTC, tibi2303 commented on src/themes/ucpkn/src/data/project/data.js
> +const drupalAttribute = require("drupal-attribute");
added inside the feature package

2022-03-04 10:07 UTC, tibi2303 commented on src/compositions/bcl-project/__snapshots__/project.test.js.snap
> +          Summary
I added a new test for ucpkn but i don't see why there are a lot of changes, as you can inspect it a bit, is a matter of a div removed for description lists and a div added in gallery

2022-03-04 10:08 UTC, tibi2303 commented on src/compositions/bcl-project/__snapshots__/project.test.js.snap
> +          Summary
also whitespaces fixed.

2022-03-04 13:21 UTC, planctus commented on src/compositions/bcl-project/data/ucpkn/data_extra_details.js
> +      {
why these, what are these for? it seems a broken behaviour this way..

2022-03-04 13:23 UTC, planctus commented on src/themes/ucpkn/src/stories/project.story.js
> +        url: "https://www.figma.com/file/NQlGvTiTXZYN8TwY2Ur5EI/BCL-Features?node-id=4298%3A144965",
don't we have a figma for this..? It seems this link currently points to version 1.1 of this feature, which is really confusing since we are demoing v1

2022-03-04 13:24 UTC, planctus commented on src/themes/ucpkn/src/stories/project.story.js
> +
there are accessiblity issues, can you check if they are relevant and in case you fix them?

2022-03-04 13:25 UTC, planctus requested changes
I think we are kind of ok, please just check these few things, for me it's fine, let's see the designer's review

2022-03-04 15:46 UTC, tibi2303 commented on src/compositions/bcl-project/data/ucpkn/data_extra_details.js
> +      {
done.

2022-03-04 15:56 UTC, tibi2303 commented on src/themes/ucpkn/src/stories/project.story.js
> +
done. There is one that is not relevant.. when i fixed them, romain suggested to keep the heading order as it is.

2022-03-04 15:57 UTC, tibi2303 commented on src/themes/ucpkn/src/stories/project.story.js
> +        url: "https://www.figma.com/file/NQlGvTiTXZYN8TwY2Ur5EI/BCL-Features?node-id=4298%3A144965",
done.

2022-03-07 09:27 UTC, planctus approved these changes

2022-03-08 08:26 UTC, merged