feat(content-banner): Added links in content banner - OEL-1359
openeuropa/bootstrap-component-library pull request #307
Opened 2022-03-23 15:21 UTC by tibi2303

2022-03-24 12:57 UTC, planctus requested changes
I don't understand the reason why you added a story only in chromatic, basically how will the users see that there is this option now available in the content banner..? Please add a control as a toggle for those links in the default story, not showing them by default.

2022-03-24 13:32 UTC, planctus commented on src/compositions/bcl-content-banner/content-banner.story.js
>  import contentBanner from "@openeuropa/bcl-content-banner/content-banner.html.twig";
We need to add the file extension to have the panel showing "source" code, so import data.js and this will be shown in the "data" panel

2022-03-25 07:41 UTC, tibi2303 commented on src/compositions/bcl-content-banner/content-banner.story.js
>  import contentBanner from "@openeuropa/bcl-content-banner/content-banner.html.twig";
added the links on the chromatic stories (small image and large image)

2022-03-25 11:55 UTC, planctus commented on src/components/bcl-card/card.html.twig
> +    <div class="mt-2-5">
i don't understand why taking more space, then you might have one badge and one link and it doesn't make sense but this is on the design side..

2022-03-25 11:58 UTC, planctus commented on src/components/bcl-card/card.html.twig
> +          attributes: _link.attributes.addClass('mb-2')
am i wrong or you are setting a margin bottom on an inline element here..? :)
I wonder if it wouldn't be better to wrap the element with a span anyhow instead of setting attributes to be passed for a class to appear..

2022-03-25 11:59 UTC, planctus commented on src/compositions/bcl-content-banner/content-banner.story.js
> +    delete data.links;
by the way it look pretty bad with badges, links and action button..but i guess that it's like this..

2022-03-25 12:08 UTC, planctus commented on src/components/bcl-card/card.html.twig
> +      {% block card_link %}
but...why is this a block..? how would they use this inside a loop..? if you want to make it a twig block this has to include all the loop..i see that the same has been done for the badges but i don't really understand how this would serve any scope..

2022-03-25 12:09 UTC, planctus requested changes
We need to fix the markup and the style of the links and i don't get these two blocks we are adding inside a loop, let's fix it also for the badges that was probably already in place..

2022-03-25 12:15 UTC, planctus commented on src/compositions/bcl-content-banner/test-content-banner.story.js
>    title: "Compositions/Content banner",
didn't you mention the possibility to add also the action button, why you didn't do it, then..? :)

2022-03-25 14:49 UTC, tibi2303 commented on src/compositions/bcl-content-banner/test-content-banner.story.js
>    title: "Compositions/Content banner",
Added the action button in a separate file and included it the same as the links.

2022-03-25 14:49 UTC, tibi2303 commented on src/components/bcl-card/card.html.twig
> +          attributes: _link.attributes.addClass('mb-2')
redone that

2022-03-28 07:17 UTC, planctus commented on src/components/bcl-card/card.html.twig
> +      {% block card_link %}
But..the idea of setting a block for a content that involves the include of a component is not wrong, potentially this could be overridden in order for them to use their own include, what was wrong was defining that block inside a loop. So, put the blocks back but include the whole loops.

2022-03-28 07:20 UTC, planctus commented on src/components/bcl-card/card.html.twig
> +            attributes: _link.attributes.addClass('me-4-5')
i still don't see the reason why not wrapping these links and badges with whatever, a span,  instead of checking for attributes, creating them if not in place and adding a class to an element, it seems an overhead to me.

2022-03-28 08:18 UTC, tibi2303 commented on src/components/bcl-card/card.html.twig
> +      {% block card_link %}
indeed, i readded then properly and also repositioned the action_button after the service_links, now we can support both inside content_banner

2022-03-28 10:56 UTC, planctus approved these changes

2022-03-28 10:57 UTC, merged