feat(modal): Add missing bootstrap params - FRONT-2686
openeuropa/bootstrap-component-library pull request #31
Opened 2021-07-27 17:37 UTC by papegaill

2021-07-28 08:27 UTC, planctus requested changes

2021-07-28 08:27 UTC, planctus commented on src/components/bcl-modal/modal.html.twig
> +{% if _static_backdrop %}
I don't think it's particularly convenient here to use drupal attributes here, basically we do that when we include a template and therefore we can expect some attributes coming from drupal, here we can simply "statically" define them.

But anyway, for how you are setting the attributes here, the static_backdrop parameter will never set the relative attribute, the dialog_attributes (it should be a local variable in case you want to keep using it) gets reset right after, indeed.

I think we should also add test for the new parameters, and in this case that would show that this data-bs-backdrop would not be set.

2021-07-28 08:27 UTC, planctus commented on src/components/bcl-modal/modal.html.twig
> +{% set _size = size ? 'modal-' ~ size %}
I find this a bit inconsistent now, shouldn't we do the same as you did for the new parameter, our local variable should only be a "copy" of the "public" one and then checking for its value we would set the associated class.

2021-07-28 08:27 UTC, planctus commented on src/components/bcl-modal/modal.html.twig
> +{% set dialog_attributes = create_attribute().addClass([
With this approach i see that we are adding an empty white space in one test, we normally create the array of classes so that it doesn't contain empty ones and then pass it to addClass(). Still mind the previous comment, might not be needed to use drupal attributes here, but it doesn't harm if we do it correctly.

2021-07-28 08:27 UTC, planctus commented on src/components/bcl-modal/modal.html.twig
> +{% set _id = id|default('modal' ~ random(1000)) %}
mmh..not so important, but can we add a dash before the random numbering..? `modal-`

2021-07-28 08:27 UTC, planctus commented on src/components/bcl-modal/modal.html.twig
> +{% set _static_backdrop = static_backdrop|default(false) %}
It looks like these new parameters  have not been added in the doc block at the top..

2021-07-28 08:27 UTC, planctus commented on src/components/bcl-modal/modal.story.js
> +    static_backdrop: {
We normally use "human readable" labels for the controls, not necessarily the parameter name when it contains underscores, so here you would add a `name` property.

2021-07-28 08:27 UTC, planctus commented on src/components/bcl-modal/modal.story.js
> +      defaultValue: false,
In another pull request these defaultValue has been removed everywhere and rewritten in a different way following the deprecation in storybook.
I would merge that since it affects all the components, once that is done you would use the same approach for the definition of the defaultValue(s) of the controls, ok?

2021-07-30 11:15 UTC, papegaill commented on src/components/bcl-modal/modal.html.twig
> +{% if _static_backdrop %}
Thanks for the static_backdrop, it's fixed now. but I don't see why we just have to limit the use of attributes for elements that should receive attributes. personally I find it cleaner than making a condition for each class. I also corrected the extra empty space.

2021-07-30 11:15 UTC, papegaill commented on src/components/bcl-modal/modal.html.twig
> +{% set dialog_attributes = create_attribute().addClass([
fixed

2021-07-30 11:15 UTC, papegaill commented on src/components/bcl-modal/modal.story.js
> +    static_backdrop: {
I don't see the point here, can you clarify? There is plenty of underscore parameter in the stories.. cards, button, etc..

2021-07-30 11:15 UTC, papegaill commented on src/components/bcl-modal/modal.story.js
> +      defaultValue: false,
Waiting to merge that PR ..

2021-07-30 12:31 UTC, papegaill commented on src/components/bcl-modal/modal.html.twig
> +{% if _static_backdrop %}
Ok, I changed the approach as you suggested, thanks for recommandation!

2021-07-30 12:37 UTC, papegaill commented on src/components/bcl-modal/modal.story.js
> +      defaultValue: false,
fixed

2021-07-30 13:04 UTC, planctus requested changes

2021-07-30 13:04 UTC, planctus commented on src/components/bcl-header/__snapshots__/header.test.js.snap
> -      class="modal-dialog modal-fullscreen"
I think you forgot the size in the template :)
But, for consistency i would use the same approach as in the other attrs, define the local variable as "empty" in case it is not set and then when you "define" the class when you create it.

2021-07-30 13:29 UTC, papegaill commented on src/components/bcl-modal/modal.test.js
> +  test("renders correctly with verticaly centered modal", () => {
yes 👍

2021-07-30 13:36 UTC, planctus approved these changes

2021-07-30 13:46 UTC, merged