feat(badge): Added hover/focus state - OEL-1560
openeuropa/bootstrap-component-library pull request #346
Opened 2022-05-06 07:21 UTC by tibi2303

2022-05-10 12:48 UTC, planctus requested changes

2022-05-10 12:48 UTC, planctus commented on src/compositions/bcl-group/__snapshots__/group.test.js.snap
> +                href="#"
can we use /example.html for all these urls..?

2022-05-10 12:48 UTC, planctus commented on src/components/bcl-badge/badge.html.twig
> +  {% set _url = _url|default('#') %}
but why this default..?
But why this logic, i'd say..? So now if it's disimissible is always going to be a link with a # as default url, don't think this was the idea..

2022-05-10 12:48 UTC, planctus commented on src/components/bcl-badge/badge.html.twig
>    {% set _classes = _classes|merge(['text-dark']) %}
Considering the amount of css we are producing for these badges it feels this might actually come from the css directly..but ok

2022-05-10 12:48 UTC, planctus commented on src/themes/joinup/src/scss/oe-bcl-joinup.scss
> +@import "@openeuropa/bcl-theme-joinup/src/scss/badge";
do we need to rename this file..? I see you did it for consistency, but this could potentially create an issue on the application side, i wouldn't do it..

2022-05-11 07:11 UTC, tibi2303 commented on src/components/bcl-badge/badge.html.twig
> +  {% set _url = _url|default('#') %}
I am setting this as a url for the focus behaviour (tab navigation), being <span> can't really be used this behaviour. Also i am using preventDefault() in the initBadges util function.
I changed the behaviour of removable action to the whole bagde as i talked with romain because it would be better to have a bigger clickable area.

2022-05-13 07:37 UTC, planctus commented
veeeeery nice, so much better, can i ask you to add stories in chromatic to test these statuses you added..?
Hover and focus, then it would be nice also to have one story where you click on the close icon to test the "new" functionality but the resulting screenshot would be entirely blank so it's not probably worth.. :)

2022-05-16 10:43 UTC, planctus approved these changes

2022-05-18 12:42 UTC, merged