feat(events): Adding time information,  aligning with figma mockup, adding controls - OEL-1695
openeuropa/bootstrap-component-library pull request #375
Opened 2022-06-10 13:59 UTC by planctus

2022-06-13 11:43 UTC, papegaill requested changes

2022-06-13 11:43 UTC, papegaill commented on src/compositions/bcl-event/event.story.js
> +FullPage.parameters = {
Strange link color in the footer of this story:
<img width="749" alt="Screenshot 2022-06-13 at 13 24 30" src="https://user-images.githubusercontent.com/1289480/173343527-61ad7cca-4359-4024-8f01-8d684e6c220c.png">

2022-06-13 11:43 UTC, papegaill commented on src/compositions/bcl-event/event.story.js
> +FullPage1.parameters = {
<img width="1093" alt="Screenshot 2022-06-13 at 13 28 10" src="https://user-images.githubusercontent.com/1289480/173344178-340fa110-f6b9-4b58-bf7e-961ce9c1a98c.png">

- date-block date should be 17 OCT - 21 OCT in this case
- date-block width is larger in figma 160px, here we have 120px
- spacing between date-block and card content is to wide compare to figma, date-block seems lost

figma:
<img width="535" alt="Screenshot 2022-06-13 at 13 33 05" src="https://user-images.githubusercontent.com/1289480/173344815-7bbc9110-ac9e-417c-8688-dbad9de9a056.png">

2022-06-13 11:43 UTC, papegaill commented on src/compositions/bcl-event/event.story.js
> +FullPage1.parameters = {
- on figma "Register now" button is full-width on mobile
- label is "Register" insteed of "Register now"

2022-06-13 11:43 UTC, papegaill commented on src/compositions/bcl-event/event.story.js
> +FullPage.parameters = {
Same for the language and log-in buttons in the header

2022-06-14 08:49 UTC, planctus commented
thanks @papegaill, for being just an update on a single feature this involved many changes here and there, which are hopefully improvements, i checked for "regressions" myself but in any case i will make a build on chromatic to see the results in the screenshots diff.

2022-06-14 11:28 UTC, papegaill approved these changes

2022-06-16 13:49 UTC, merged