chore(dummy-text): Adding utility, replacing in every story - OEL-1744
openeuropa/bootstrap-component-library pull request #388
Opened 2022-06-23 11:28 UTC by planctus

2022-06-24 07:45 UTC, tibi2303 commented on src/components/bcl-card-layout/__snapshots__/card-layout.test.js.snap
> +          <p />
It's adding some closed p tags.

2022-06-24 13:29 UTC, planctus commented on src/components/bcl-card-layout/__snapshots__/card-layout.test.js.snap
> +          <p />
Yep, it was by default wrapping in a <p> tag, but in many cases there was already a paragraph in place, so i made it by default plain text.

2022-06-27 07:46 UTC, tibi2303 approved these changes

2022-06-27 08:39 UTC, tibi2303 requested changes
At code level, it's ok, but the design look weird now.
![image](https://user-images.githubusercontent.com/36895476/175897232-21680b4d-3213-42c7-9092-203e8ba23293.png)

Also in some place we don't have text at all
![image](https://user-images.githubusercontent.com/36895476/175897282-bb9a03b9-ef84-45a2-b388-f37aa18544b5.png)

2022-06-28 07:57 UTC, tibi2303 approved these changes

2022-06-28 07:57 UTC, merged