feat(description-list): Description List refactor: OEL-2014
openeuropa/bootstrap-component-library pull request #447
Opened 2022-09-08 10:17 UTC by tibi2303

2022-09-12 06:55 UTC, planctus commented on src/compositions/bcl-description-list/data/data--horizontal.js
> +      definition: {
did you agree with backend about this change..? it's always confusing, we had a request to make the label size configurable and we went for a full refactoring here..

2022-09-12 12:16 UTC, brummbar requested changes

2022-09-12 12:16 UTC, brummbar commented on src/compositions/bcl-description-list/description-list.html.twig
> +    <dl class="row mb-0">
Like this we are still rendering multiple `<dl>`, but we should have only one that wraps the all the component.

2022-09-12 12:16 UTC, brummbar commented on src/compositions/bcl-description-list/description-list.html.twig
> +{% if _col_size is not empty %}
In the call we said to allow to pass classes, so it leaves more freedom to the user. They could define the behaviour different based on viewport, so this just leaves too many combinations possible.

2022-09-12 12:55 UTC, tibi2303 commented on src/compositions/bcl-description-list/description-list.html.twig
> +          {%- include '@oe-bcl/bcl-description-list/description-list-details.html.twig' with _item.definition only -%}
the support for single strings is no longer available, this line is about the support of array of object or single object.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/36895476/189659126-b8dd6fda-fa10-4379-85b1-b4bc13a3e016.png">

2022-09-12 13:01 UTC, tibi2303 commented on src/compositions/bcl-description-list/description-list.html.twig
> +    <dl class="row mb-0">
the markup is no longer correct if we have a dl for all in the horizontal layout.

The problem is that the DL tag supports only one layer inside of DIV tag. But for the column layout we need 2 - row and column.
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/36895476/189660434-d6a57f70-8461-42b7-8a20-6f930758ecb7.png">

2022-09-12 13:03 UTC, tibi2303 commented on src/compositions/bcl-description-list/description-list.html.twig
> +{% if _col_size is not empty %}
indeed, i change it.

2022-09-12 13:03 UTC, tibi2303 commented on src/compositions/bcl-description-list/description-list.html.twig
> +{% set _col_classes = 'col' %}
this is used for an inner tag, we set the attributes only on the root tag.

2022-09-12 13:05 UTC, tibi2303 commented on src/compositions/bcl-description-list/description-list.html.twig
> +          {%- include '@oe-bcl/bcl-description-list/description-list-details.html.twig' with _item.definition only -%}
I guess this is again overcomplicated, maybe we should only support arrays of objects and that's all. what do you think?

2022-09-12 13:09 UTC, tibi2303 commented on src/compositions/bcl-description-list/description-list.html.twig
> +{% set _col_classes = 'col' %}
also this is no longer available as i changed the parameter to directly add the class. As you said for more possibilities

2022-09-13 17:29 UTC, brummbar commented on src/compositions/bcl-description-list/description-list.html.twig
> +    <dl class="row mb-0">
Then we are doing things wrong. This was the main point of the remark, if it's a semantic description list it should have only one `<dl>`. I'll guess I'll redo the review with this in mind, but I'm quite disappointed.

2022-09-14 12:56 UTC, tibi2303 commented on src/compositions/bcl-description-list/description-list.html.twig
> +    <dl class="row mb-0">
@brummbar please have a look, I change to approach more or less the same we had before but without the extra markup. I think it should be good.

2022-09-19 16:30 UTC, brummbar commented on src/compositions/bcl-description-list/description-list.html.twig
> +          {%- include '@oe-bcl/bcl-description-list/description-list-details.html.twig' with _item.definition only -%}
> the support for single strings is no longer available
This we can never ever do. We cannot drop support, especially between minors.

In general though, we should always simplify. It should have always supported only one scenario, the array of objects. Or better, we should have supported markup without any additional icon. Users could put the icons by themselves.

2022-09-21 11:06 UTC, brummbar requested changes

2022-09-23 17:03 UTC, brummbar requested changes
I see that now when I have two terms and then one definition, there's extra space between the terms:

![image](https://user-images.githubusercontent.com/8488617/192014176-f2cf0f55-3cd9-4740-babc-29424728a5f8.png)

2022-09-23 17:03 UTC, brummbar commented on src/compositions/bcl-description-list/description-list.html.twig
> +  - horizontal_size (string) (default: '3-9')
In the call we said to drop this and use multiple dl plus normal row/col classes, why it wasn't implemented?

2022-09-23 23:34 UTC, tibi2303 commented on src/compositions/bcl-description-list/description-list.html.twig
> +  - horizontal_size (string) (default: '3-9')
indeed, i was focused on the points in this pr and may have missed that, anyway it's pushed

Also regarding the spacing, it may be the case on your side only
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/36895476/192069465-af355f83-1cd7-4fdd-9223-5bc6b402677e.png">

I guess this 'new' implementation will not have this bug anymore but tell me if it's still happening.

2022-09-27 13:44 UTC, brummbar commented
We have issues on smaller viewports:
![image](https://user-images.githubusercontent.com/8488617/192543424-a56c40cd-5d90-4b33-8c19-2d85ecc84bb1.png)

cc @emeryro

2022-09-27 14:06 UTC, brummbar approved these changes

2022-09-28 08:32 UTC, merged