feat(pagination): Refactored pagination - OEL-2061
openeuropa/bootstrap-component-library pull request #462
Opened 2022-09-27 13:01 UTC by tibi2303

2022-09-30 11:24 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set attributes = attributes.addClass(_classes)%}
can you add a space before the closing tag?

2022-09-30 11:27 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {%- if _icon is not empty -%}
why this indentation here..?

2022-09-30 11:30 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +<a
can't we write it like this:
```
{%- if _path is not empty -%}
<a
{% else %}
<div
{%- endif -%}
  {{- attributes -}}
>
```

2022-09-30 11:47 UTC, planctus commented on src/data/pagination/data.js
> +      label: "...",
why are we adding this..? I see this in the examples in figma, but i find it confusing because it makes you think that a pop-up would reveal the hidden items, instead here we demo it as a dead element..are we sure about doing this?

2022-09-30 11:48 UTC, planctus commented on src/compositions/bcl-content-banner/content-banner.html.twig
> -      options: ['sm', 'md', 'lg', 'xl']
but why this change is in this pull request..?

2022-09-30 12:07 UTC, planctus commented on src/components/bcl-pagination/pagination.html.twig
> +            label: '<span aria-hidden="true">&lsaquo;</span>'
no no no no, we cannot do this. When do you see us storing html in a prop, tiberiu..? The problem with this is that once you will go rendering it, it will be escaped, not in storybook because we have the twig autoescape disabled, but in drupal it will. 
This can only be done for internal variables that we then render with |raw

2022-09-30 12:09 UTC, planctus commented on src/components/bcl-pagination/pagination.html.twig
> +              label: '<span aria-hidden="true">&laquo;</span>'
also here, i know this will make the refactoring trickier but this has to be avoided.

2022-09-30 12:11 UTC, planctus requested changes
Mainly the problem is about passing html in props, there are a few other remarks, but simple ones.
I thought this would have been a deeper refactoring taking out some logic from the main template, but still we avoid lots of repeated code, that is good.

2022-10-02 16:19 UTC, tibi2303 commented on src/compositions/bcl-content-banner/content-banner.html.twig
> -      options: ['sm', 'md', 'lg', 'xl']
This is the small update of docs regarding the content banner that we spoked on friday. Should I create a new pr only for this line?

2022-10-02 16:24 UTC, tibi2303 commented on src/data/pagination/data.js
> +      label: "...",
We have this ticket in the backlog regarding the missing ellipsis and I thought about providing it as a demo. Also before this pr, dead elements ( with root div tags ) were not possible, we could only provide elements with anchor tag as root with href="#".

2022-10-02 16:25 UTC, tibi2303 commented on src/data/pagination/data.js
> +      label: "...",
Maybe the behaviour could be improved but i though this should be default..

2022-10-02 16:35 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +<a
used an internal variable for this, also for the closing tag.

2022-10-02 16:35 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {%- if _icon is not empty -%}
changed

2022-10-02 16:35 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set attributes = attributes.addClass(_classes)%}
i don't no need anymore, no?

2022-10-02 16:37 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +            label: '<span aria-hidden="true">&lsaquo;</span>'
Changed the approach, used the possibility for 2 different arrow (double and simple) for each left and right using a new param character_label.

2022-10-02 16:37 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +              label: '<span aria-hidden="true">&laquo;</span>'
changed.

2022-10-03 06:43 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set attributes = attributes.addClass(_classes)%}
why not tiberiu..? 
`{% set attributes = attributes.addClass(_classes) %}`

2022-10-03 06:49 UTC, planctus commented on src/compositions/bcl-content-banner/content-banner.html.twig
> -      options: ['sm', 'md', 'lg', 'xl']
`Should I create a new pr only for this line?` Yes, prs are for free, if you make this in a dedicated pr this fix will be tracked in a ticket and in the changelog, like this this is a custom branch and as long as we will deal with this pr the code in development will not be fixed and once we do it there will be no track of that.

2022-10-03 06:53 UTC, planctus commented on src/components/bcl-pagination/pagination.html.twig
> +            label: '<span aria-hidden="true">&lsaquo;</span>'
what did you do..? :) 
So now this is parametric without any default set..? You mean that in a current implementation, without setting this param, they would not have anything printed for those arrows..?
Who asked you to create the possibility of using alternative charachters, did i miss this..?
I ask you to fix something that would break and you make something that will break even more.?
It was ok like it was before you touched this, unless we received new requirements i'm not aware of.

2022-10-03 06:56 UTC, planctus commented on src/data/pagination/data.js
> +      label: "...",
So, basing on a ticket that never got validated, you did something in this pr that was only supposed to split the templates..?
Are we looking for troubles ourselves..? Why should we support dead elements..? Did you receive requirements about this..? If we will discuss about waht BE requested about these "dots" and we come out with clear requirements we do something about it, otherwise i don't see any reason why we shuld introduce this weak point in the component, demoing that.

2022-10-03 07:13 UTC, tibi2303 commented on src/data/pagination/data.js
> +      label: "...",
It's removed

2022-10-05 07:24 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set _character = '' %}
this is a leftover

2022-10-05 07:26 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set _character = '' %}
removed

2022-10-05 07:39 UTC, planctus commented on src/components/bcl-pagination/pagination.html.twig
> -      - icon (Icon component)
do we really have to repeat the same set of props for all of these objects..? can't we reduce a bit this doc comment, it seems really redundant to repeat 4 times the same data structure. Place the items one after the other and then you add a single "format" key where you detail the props

2022-10-05 07:51 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> -      - icon (Icon component)
removed and kept only for the items, i think it should be clear enough.

2022-10-05 10:11 UTC, planctus commented on src/components/bcl-pagination/pagination.html.twig
> +            {% set _first = _first|merge({
So..this template got simplified but now it really looks for what it is, instead of working with a single items array where to loop and include the item template, we process the four "special items" separately and in between them we process the "standard" items, now the challenge is:
can't we build a single items array in this template basing on the current data set and include the item template only once..?

2022-10-05 14:04 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +            {% set _first = _first|merge({
done

2022-10-05 15:33 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {% set _label = '' %}
did we have this..? but in any case, why doing it..? :)

2022-10-05 15:48 UTC, planctus commented on src/components/bcl-pagination/pagination.story.js
> +    icon_path: {
mmhh....i don't understand, how is this something like a "Path to custom icons sprite", we hardcode the icon names if you pass this stuff, so this is the path to our sprite only.
It's good that you added this control and it's also good that you created it as a boolean, but the meaning of it it's not really the one you gave it. 
If you really want to be super descriptive, you can rename this in:
`path to bcl sprite file (icon_path)`
and in the description you say that
`items like prev, next, first, last will be rendered as icons instead of an html entity, it is still possible to pass a custom icon objects along those items to use custom icons.`

2022-10-06 12:03 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% if _icon is empty %}
indeed, it's changed

2022-10-06 12:03 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {% set _icon_name = "" %}
added it in the first condition

2022-10-06 12:03 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% elseif _icon.path is empty and _icon_path is not empty %}
yes, changed

2022-10-06 12:04 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +
added it in the first condition

2022-10-06 12:14 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {% if _icon.name is not empty %}
why don't you move this check, but using `_icon_name is not empty` so to include also the _icon object definition..?

2022-10-06 12:31 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {% if _icon.name is not empty %}
done

2022-10-06 12:39 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {% if _icon_name is not empty %}
here we don't know if we have a path to the icons, this is the moment when we should decide whether to build the icon object or to set the fallback html entities label.

2022-10-06 12:42 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% if _icon_html is not empty and _icon_path is empty %}
as written above this can be integrated in the main "processing" logic.
if you have the icon_path you build the object, if you don't but you have a icon_html set then you set the html entity as the label

2022-10-06 12:50 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% if _icon_html is not empty and _icon_path is empty %}
done

2022-10-06 13:34 UTC, planctus commented on src/components/bcl-pagination/pagination.story.js
> +import demoData from "@openeuropa/bcl-data-pagination/data";
why removing this extension..? You don't want this code to appear in the panel..?

2022-10-06 13:37 UTC, planctus commented on src/components/bcl-pagination/pagination.story.js
> +    data.first.label = "";
is this a leftover of when we were rendering both..?

2022-10-06 13:41 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.story.js
> +    data.first.label = "";
done, removed

2022-10-06 13:41 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.story.js
> +import demoData from "@openeuropa/bcl-data-pagination/data";
leftover from when i tested the listing data, rolled back

2022-10-07 06:46 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {% set attributes = attributes.setAttribute('href', _path ) %}
You can remove this, this is now happening in the link template

2022-10-07 06:52 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {% set attributes = attributes.setAttribute('href', _path ) %}
Removed, also removed the disabled, it's done also in the link

2022-10-07 06:58 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% if _disabled %}
this is also duplicated, the same happens in the link template (with an additional and useless disabled class), you can simply pass disabled to the link, then. ;)

2022-10-07 07:00 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% if _disabled %}
done, it's removed

2022-10-07 07:03 UTC, planctus commented on src/components/bcl-pagination/pagination.html.twig
> +  {% set _first = _first|merge({position: 'first'}) %}
can you add spaces after and before curly brackets..?

2022-10-07 07:05 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +  {% set _first = _first|merge({position: 'first'}) %}
pushed

2022-10-07 07:13 UTC, planctus commented on src/components/bcl-pagination/pagination.html.twig
> +{% set _internal_items = [] %}
can you move this logic under all the {% set %}, first we process all the attributes of the pagination, then we take care of the items to render

2022-10-07 07:16 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +{% set _internal_items = [] %}
done

2022-10-07 07:17 UTC, planctus commented on src/components/bcl-pagination/pagination.html.twig
> +  {% if _internal_items is not empty and _internal_items is iterable %}
at line 93 we set a _class variable, it seems a leftover of something, don't even know what..

2022-10-07 07:34 UTC, planctus commented on src/components/bcl-pagination/pagination.html.twig
> +{% if _first is defined and _first is not empty %}
these conditions do not make much sense, if you set the variables default then there is no need to check for `is defined`, otherwise you don't set any default and in that case you check also for the definition of the variable.

2022-10-07 07:37 UTC, planctus commented on src/components/bcl-pagination/pagination.html.twig
>  {% if _aria_label is not empty %}
It's not clear to me the reason why we support this parameter, is it for backward compatibility..? In that case i think we should deprecate it and recommend the usage of attributes, this also means not setting it in our specs as "aria_label" but as an attribute.

2022-10-07 07:38 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
>  {% if _aria_label is not empty %}
then it's the case also for the item

2022-10-07 07:45 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set _position = position|default('') %}
i think we should separate internal variables from the parameters, although technically there is no difference, if you look at this doc you might think that the position parameter needs to be added and passed along the items.
Create an "internal parameters" section in the doc where to put position, enable_*, aria_label might stay again for backward compatibility but it should be deprecated in favor of attributes and in our specs this should be the way to set this attribute.

2022-10-07 07:54 UTC, planctus commented on src/components/bcl-pagination/pagination.story.js
>  Default.args = getArgs(demoData);
there is no param in this function, no need to pass the data.

2022-10-07 08:22 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.story.js
>  Default.args = getArgs(demoData);
done

2022-10-07 08:22 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set _position = position|default('') %}
done, added also icon_path in the internal section and updated the specs for all paginations

2022-10-07 08:22 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
>  {% if _aria_label is not empty %}
removed

2022-10-07 08:23 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +{% if _first is defined and _first is not empty %}
removed is defined from all checks

2022-10-07 08:24 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.test.js
> +
added a test for next with a custom icon

2022-10-07 10:04 UTC, planctus commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set _position = position|default('') %}
When i said we should deprecate it, it means really adding a "deprecated, use attributes" text to its line in the doc.
But i think that you removed aria_label from the pagination template, it's the same as here, to be deprecated but not removed

2022-10-07 10:09 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set _position = position|default('') %}
ok, done

2022-10-07 10:49 UTC, planctus approved these changes

2022-10-19 14:11 UTC, drishu requested changes

2022-10-19 14:11 UTC, drishu commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {% endif %}
all these checks are overly complicating things, in the parent template, where you merge the positions, instead, just set the appropriate icon data.

2022-10-19 14:11 UTC, drishu commented on src/components/bcl-pagination/pagination.html.twig
> +{% if _first is not empty %}
once you move some of the icon logic for these first last next prev items here, if some logic repeats, you could create a marco

2022-10-19 14:11 UTC, drishu commented on src/components/bcl-pagination/pagination.story.js
> +    icon_path: {
It's flouting a feature that I dont like, I'd remove this but I'll leave that up to next reviewer

2022-10-19 14:11 UTC, drishu commented on src/data/pagination/data--listing.js
> +    .addClass(["mt-4-5"])
why do we need this margin ? I know it was there before, but why

2022-10-20 11:21 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +    {% if _icon_html is not empty %}
changed as we spoke

2022-10-20 11:21 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +  Internal Parameters
changed

2022-10-20 11:22 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set attributes = attributes.addClass(_classes) %}
changed

2022-10-20 11:23 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +  {% endif %}
changed, add it in the parent and moved the icon logic in the child

2022-10-20 11:23 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +{% if _first is not empty %}
no need for macro anymore

2022-10-20 11:24 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.story.js
> +    icon_path: {
it's just to exemplify the way icon_path logic works in the pagination, it does not impact the template in any way.

2022-10-20 11:24 UTC, tibi2303 commented on src/data/pagination/data--listing.js
> +    .addClass(["mt-4-5"])
this i am a bit uncertain to change it in the parent template.

2022-10-21 07:35 UTC, drishu commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set attributes = attributes.addClass(_classes) %}
maybe not pushed ?

2022-10-21 07:38 UTC, drishu commented on src/components/bcl-pagination/pagination.story.js
> +    icon_path: {
I see you insist on it, so I'll leave to a 3rd party to decide, @brummbar what do you think?

2022-10-21 07:39 UTC, drishu commented on src/data/pagination/data--listing.js
> +    .addClass(["mt-4-5"])
ok, lets leave it for now to not impact existing sites

2022-10-21 07:46 UTC, drishu requested changes

2022-10-21 07:46 UTC, drishu commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set _disabled = disabled|default(false) %}
I missed these the first time around, enywhere we have booleans and we want to set defaults we should use `?? true` or `?? flase`

2022-10-21 07:59 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set attributes = attributes.addClass(_classes) %}
If i move it when we create_attributes, the classes will not be added when the attributes comes from data

2022-10-21 08:06 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set _disabled = disabled|default(false) %}
I changed it, i will create a ticket to change it in all the templates.

2022-10-21 08:06 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% set _enable_prev_next_icon = enable_prev_next_icon|default(false) %}
done, indeed, i may have missed it

2022-10-21 08:07 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +  Internal Parameters
deleted all together

2022-10-21 10:04 UTC, drishu approved these changes

2022-10-26 14:45 UTC, brummbar commented on src/components/bcl-pagination/pagination.story.js
> +    icon_path: {
Let's leave it for now, since it's too late to remove the whole icon idea.

2022-10-27 08:21 UTC, merged