feat(documentation): Updated documentation - OEL-2078
openeuropa/bootstrap-component-library pull request #472
Opened 2022-10-05 09:30 UTC by tibi2303

[skip chromatic]

2022-11-17 18:39 UTC, drishu requested changes
all these "array of this that object", I dont like it, we have to find a good naming convention and then append "[]", like `object[]`

2022-11-17 18:39 UTC, drishu commented on src/compositions/bcl-file/file.html.twig
> +  - translation (translation Object) (default: {}) format: {
if we take the name of the template as the base of the "object" name, then it should be:
```suggestion
  - translation (file translation Object) (default: {}) format: {
```

2022-11-17 18:39 UTC, drishu commented on src/compositions/bcl-header/header.html.twig
> +    - options: ['ec', 'neutral']
shouldn't it be the same options as for the footer ?

2022-11-17 18:39 UTC, drishu commented on src/compositions/bcl-language-switcher/language-switcher.html.twig
> +  - id (string) (default: collapse-random(1000)) - collapse custom id - optional
```suggestion
  - id (string) (default: collapse-random(1000), optional)
```
seemed a bit confusing, lets simplify

2022-11-17 18:39 UTC, drishu commented on src/compositions/bcl-listing/listing.html.twig
> +  - items: (array of objects of type card)
```suggestion
  - items: (card[])
```

2022-11-17 18:39 UTC, drishu commented on src/compositions/bcl-recent-activities/recent-activities.html.twig
> +  - activities (array of object) (default: [])
```suggestion
  - activities (object[]) (default: [])
```

2022-12-05 14:00 UTC, tibi2303 commented on src/compositions/bcl-content-banner/content-banner.html.twig
> -    - content: (string)
done, included the ones that can be used inside the content-banner

2022-12-05 14:01 UTC, tibi2303 commented on src/compositions/bcl-content-banner/content-banner.html.twig
> +    - date: (object) (default: {})
changed them to `{component} object` format

2022-12-05 14:01 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +  - translation (translation Object) (default: {}) format: {
changed

2022-12-05 14:01 UTC, tibi2303 commented on src/compositions/bcl-listing/listing.html.twig
> +  - items: (array of objects of type card)
changed

2022-12-05 14:01 UTC, tibi2303 commented on src/compositions/bcl-recent-activities/recent-activities.html.twig
> +  - activities (array of object) (default: [])
changed

2022-12-17 09:55 UTC, drishu commented on src/compositions/bcl-header/header.html.twig
> +    - options: ['ec', 'neutral']
header takes the bcl-header--neutral, bcl-header--ec and bcl-header--eu classes, at least in bcl 24.1, if this changed revert it, or maybe I'm not understanding something ?

2022-12-18 10:01 UTC, tibi2303 commented on src/compositions/bcl-header/header.html.twig
> +    - options: ['ec', 'neutral']
ah, you are right, it may confusing because we have the --eu variant as default, it's added

2022-12-19 12:09 UTC, drishu approved these changes

2023-01-09 09:51 UTC, merged