feat(badges): Link inclusion - OEL-2066
openeuropa/bootstrap-component-library pull request #475
Opened 2022-10-11 10:48 UTC by tibi2303

2022-10-17 07:50 UTC, planctus commented
To me, a simpler approach that would also improve in a way the markup would be to maintain the badnge as a span and including the link as an "element" of the badge. 
so `<span class="badge"><a>Link label</a><span class-"visually-hidden">Assistive text</span><span class="icon--close"></span></span>`
Doing this would not pose any risk in terms of pre-building markup chunks to be passed to the link but itwould slightlychange the behaviour, meaning that not the whole area of the badge would be clickable due to its padding.
But i think we can take care of this style so that the a tag will actually occupy the full size of the badge as it currently is leaving the chance to click on the close icon if any.

2022-10-17 07:57 UTC, planctus commented on src/components/bcl-badge/badge.html.twig
> +  {% set _classes = _classes|merge(['bg-' ~ _background]) %}
it seems that in BS 5.2 this changed, these classes are used to set a background and color the text at once:
```
<span class="badge text-bg-primary">Primary</span>
<span class="badge text-bg-secondary">Secondary</span>
<span class="badge text-bg-success">Success</span>
<span class="badge text-bg-danger">Danger</span>
<span class="badge text-bg-warning">Warning</span>
<span class="badge text-bg-info">Info</span>
<span class="badge text-bg-light">Light</span>
<span class="badge text-bg-dark">Dark</span>
```

2022-10-19 09:20 UTC, tibi2303 commented on src/components/bcl-badge/badge.html.twig
> +  {% set _classes = _classes|merge(['bg-' ~ _background]) %}
thanks, i fixed the classes, regarding the moving of the padding to the link, i would not be able to take care of focus,hover states - changing the color of the badge.

2022-11-21 08:30 UTC, drishu requested changes
This is hard to review as there is a lot more here then the badge changes, and there should be nothing else

2022-11-21 09:28 UTC, drishu commented on src/components/bcl-badge/badge.html.twig
> +  <span class="{{ _icon_classes|join(' ') }}" aria-hidden="true">
I dont get why we need a variable for this when there is no logic modifying it before printing here

2022-12-06 14:30 UTC, tibi2303 commented on src/components/bcl-badge/badge.html.twig
> +  <span class="{{ _icon_classes|join(' ') }}" aria-hidden="true">
yes, i changed it but regarding the other changes - those are impacting also this link inclusion because of the hover effect when we have it as link so i need those changes also

2022-12-15 15:23 UTC, tibi2303 commented on src/components/bcl-badge/badge.html.twig
> +  <span class="{{ _icon_classes|join(' ') }}" aria-hidden="true">
reverted the changes and should now include only the link inclusion

2022-12-17 08:58 UTC, drishu approved these changes

2022-12-21 14:03 UTC, brummbar requested changes

2022-12-21 14:03 UTC, brummbar commented on src/components/bcl-badge/badge.html.twig
> +  {% set attributes = attributes.setAttribute('title', _title) %}
Why are we doing this? The title will be the same as the link title:
![image](https://user-images.githubusercontent.com/8488617/208923532-9282b098-ddee-4c23-b74b-f4e28b9343c1.png)

2023-01-02 08:49 UTC, tibi2303 commented on src/components/bcl-badge/badge.html.twig
> +  {% set attributes = attributes.setAttribute('title', _title) %}
I changed the approach, kept the title but it's no longer the default as the label. It is only added if the title is added by the user.

2023-01-06 13:05 UTC, brummbar approved these changes

2023-01-08 12:11 UTC, merged