feat(gallery): Raw filter used and fixed more items - OEL-2093
openeuropa/bootstrap-component-library pull request #479
Opened 2022-10-25 10:52 UTC by tibi2303

2022-12-12 18:00 UTC, drishu requested changes
For now that's it, haven't checked if the reported issues are resolved, I'll do that after first round of feedback is implemented.

Was also thinking if it would make more sense to revert to the 24.1 variant, apply the patch, and check if there is anything else needed to fix the issues, but we need to discuss that with @brummbar

2022-12-12 18:00 UTC, drishu commented on src/compositions/bcl-gallery/gallery.html.twig
> +    <div class="bg-lighter py-3 px-4 mt-2 rounded text-center">
this stuff used to be wrapped in an if so that it appears only when needed, if there ar no proper rendering tests no wonder this regression happened somewhere down the line.

2022-12-12 18:00 UTC, drishu commented on src/compositions/bcl-gallery/gallery-modal.html.twig
> +            caption_title: ('<iframe' in _item.media or '<video' in _item.media) ? '' : _item.caption_title,
there is something wrong, not sure where the issue is coming from but:
![image](https://user-images.githubusercontent.com/11507647/207112860-3b673217-bbdc-47e2-8dc0-2ae0170cf9c5.png)
if you need to repro let me know and we can do it on my Drupal instance.

2022-12-12 18:00 UTC, drishu commented on src/compositions/bcl-gallery/gallery.html.twig
> +      <a
if I have more than 5 items, and I click this link, nothing happens

2022-12-12 18:00 UTC, drishu commented on src/components/bcl-carousel/carousel.html.twig
> +      {{ _item.image|raw }}
why do we need this ?

2022-12-12 18:00 UTC, drishu commented on src/compositions/bcl-gallery/gallery-item.html.twig
>      {% endif %}
I see `<p class="fs-5">{{ _item.caption_title }}</p>` but the patch has a h5, I thought first that since there is a gallery-item is the reason why we dont have the macro from the patch, but now I see this, was the patch applied or not ?

2022-12-12 18:00 UTC, drishu commented on src/compositions/bcl-gallery/gallery-item.html.twig
> +        {{ _item.caption|raw }}
why do we need this raw filter everywhere ?

2022-12-14 14:10 UTC, tibi2303 commented on src/compositions/bcl-gallery/gallery-item.html.twig
>      {% endif %}
It was applied, but i was thinking that we include the gallery-item and it's working in the same way as the macro, why do we still need it?

2022-12-14 14:13 UTC, tibi2303 commented on src/compositions/bcl-gallery/gallery-item.html.twig
>      {% endif %}
but for the p we change it to how it is now to simplify the heading in the library, it was some time ago between 24.1 and now - i can change it back to h5

2022-12-14 14:15 UTC, tibi2303 commented on src/compositions/bcl-gallery/gallery.html.twig
> +      <a
i can't reproduce it, when i click it the rest of the items are showing

2022-12-14 14:19 UTC, tibi2303 commented on src/compositions/bcl-gallery/gallery.html.twig
> +    <div class="bg-lighter py-3 px-4 mt-2 rounded text-center">
indeed, thanks for pointing this out, the if was only added for the container of the hidden thumbnails and not for this... i will add also a test for it

2022-12-14 14:30 UTC, tibi2303 commented on src/compositions/bcl-gallery/gallery-item.html.twig
> +        {{ _item.caption|raw }}
I revert all of them

2022-12-14 17:40 UTC, tibi2303 commented on src/compositions/bcl-gallery/gallery-modal.html.twig
> +            caption_title: ('<iframe' in _item.media or '<video' in _item.media) ? '' : _item.caption_title,
I tested myself on the drupal instance, I fixed it - it was because the modal had a template itself and I reverted to how it was before this template... Still weird behaviour that i could not explain is why this was happening when the template was included..

2022-12-17 06:56 UTC, drishu commented on src/compositions/bcl-gallery/gallery.html.twig
> +      <a
works now

2022-12-17 07:05 UTC, drishu commented on src/compositions/bcl-gallery/gallery-item.html.twig
>      {% endif %}
not sure, I am not familiar with this change at the moment, not sure what the impact is on drupal side, we need to discuss this in the team

2022-12-17 07:43 UTC, drishu approved these changes

2022-12-18 07:49 UTC, merged