feat(pagination): Added ellipsis support - OOEL-1523
openeuropa/bootstrap-component-library pull request #481
Opened 2022-11-03 14:08 UTC by tibi2303

2022-11-17 12:24 UTC, drishu requested changes
I remembered you have some filters disabled, I need a screenshot of what it looks like without the icons when the filter is enabled in netlify.

2022-11-17 12:24 UTC, drishu commented on src/components/bcl-pagination/pagination.html.twig
> +    icon_html: "&hellip;",
there is one problem with this, if icon_path is set we dont have anything:
![image](https://user-images.githubusercontent.com/11507647/202441696-7a99bada-9295-49ab-a95b-ecc89dc4f2fe.png)

2022-11-17 12:24 UTC, drishu commented on src/components/bcl-pagination/pagination-item.html.twig
> +  <span
why not `<span {{ attributes }}>{{ _label }}</span>` do we really need all these newlines?

2022-11-17 12:24 UTC, drishu commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% if _link %}
don't like all this with the link complicates the logic to much, why not just check if _path is empty or not?

2022-11-17 12:35 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +    {{ attributes }}
I need the .page-link class for the styling but indeed span inside span is not ok, i am changing the tag from span to div but keeping the attributes
Here is an img without the class added.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/36895476/202447761-bfb20da3-feec-48d2-aaf5-a778dbd54115.png">

2022-11-17 12:49 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +  <span
done. also changed the span into div

2022-11-17 12:49 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +    icon_html: "&hellip;",
done.

2022-11-17 12:49 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +{% if _link %}
done. indeed

2022-11-21 07:59 UTC, drishu requested changes
![image](https://user-images.githubusercontent.com/11507647/202995577-d25b8af8-6111-4be9-a3aa-272b28b359d9.png)
This is the reason I asked for the screenshot with the autofilter disabled, in Drupal, we dont have it disabled.

2022-11-21 07:59 UTC, drishu commented on src/components/bcl-pagination/pagination.html.twig
> +            icon_path: _icon_path,
why was this needed?

2022-12-06 15:17 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +            icon_path: _icon_path,
if i send the icon_path to the ellipsis items without this merge, the item will search for icon_name which is not present for ellipsis. This is related to line 96 and 86 where i add for these items the icon_path as empty in order to not be added for this specific cases.

2022-12-06 15:26 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +            icon_path: _icon_path,
also i enabled the autoescaped and added the raw filter on the icon_html inside the item. This should fix that problem and this is how it looks:
![image](https://user-images.githubusercontent.com/36895476/205953165-c09a00ea-cf10-40c2-8281-c87758c30a47.png)

2022-12-06 18:24 UTC, drishu commented on src/components/bcl-pagination/pagination-item.html.twig
> +    {{ attributes }}
ok

2022-12-06 18:28 UTC, drishu commented on src/components/bcl-pagination/pagination.html.twig
> +    icon_html: "&hellip;",
Something seems wrong with the enable_prev_next_icon

2022-12-06 18:36 UTC, drishu commented on src/components/bcl-pagination/pagination.html.twig
> +            icon_path: _icon_path,
I see ok

2022-12-06 18:47 UTC, drishu requested changes

2022-12-06 18:47 UTC, drishu commented on src/components/bcl-pagination/pagination-item.html.twig
> +      <span aria-hidden="true">{{ _icon_html|raw }}</span>
we controle the scope of icon_html but I still feel uneasy about this raw filter, I would have rather done something like 
```
{% set icon_html %}
      &hellip;
    {% endset %}
```
for all concerned

2022-12-06 19:25 UTC, tibi2303 commented on src/components/bcl-pagination/pagination-item.html.twig
> +      <span aria-hidden="true">{{ _icon_html|raw }}</span>
indeed, i think it's better like you suggested and I've redone it. Still they are internal variables so it was safe before i think

2022-12-08 08:01 UTC, drishu requested changes
.

2022-12-08 08:08 UTC, drishu approved these changes

2022-12-08 08:58 UTC, merged