feat(user-listing): Added user listing - Front 2451
openeuropa/bootstrap-component-library pull request #49
Opened 2021-08-20 08:25 UTC by tibi2303

2021-08-20 12:18 UTC, planctus requested changes
I think you should check the preview before considering a pull request ready for review, anyway it was pretty straighforward to find the issue, the implementation is pretty ok, i'm fine with the added parameters for the additional classes of the main elements of the card.
But i have a js error:
`Uncaught TypeError: Cannot read property 'addEventListener' of undefined`
which i think is causing the offcanvas not being opened by clicking on the trigger button in mobile.

2021-08-20 12:18 UTC, planctus commented on src/components/bcl-card/card.html.twig
> +  {% if _category is not empty %}
i'm not sure about this, i don't know if this would work, but ideally i would prefer these badges in the card-header more than in the body..

2021-08-20 12:18 UTC, planctus commented on src/components/bcl-card/card.html.twig
> +  {% if _card_tags is not empty and _card_tags is iterable %}
mmh..this is not so convincing...in such a scenario wouldn't this simply be the "content" of the card, why adding a new parameter for this..? I see that maybe the expectation is to have two fields to map to these tags thingy, but still this needs "work" on the implementation side to pass the object as we needed it..so this looks questionable to me.
Also the name is confusing, initially i thought that the "tags" where the badges, but you named that parameter "category", instead...

2021-08-20 12:18 UTC, planctus commented on src/compositions/bcl-user-listing/package.json
> +  "version": "0.5.0",
Well, we have just released 0.6.0, but you need to include this package in the dependencies of bcl-twig-components, otherwise the templates will not be available in any of the themes.

2021-08-30 07:13 UTC, tibi2303 commented on src/components/bcl-card/card.html.twig
> +  {% if _category is not empty %}
I moved it to header, it works but i needed to add some reset classes for the head default styles.

2021-08-30 07:13 UTC, tibi2303 commented on src/components/bcl-card/card.html.twig
> +  {% if _card_tags is not empty and _card_tags is iterable %}
Indeed, I removed this and added all in content.

2021-08-30 07:15 UTC, tibi2303 commented on src/compositions/bcl-user-listing/package.json
> +  "version": "0.5.0",
Updated everything to 0.6 and add user-listing package as a dependency in twig templates, I don't really like the naming because when we will have user-view etc we will have multiple package with almost the same name. It would be great to have one package 'user' and that to include everything regarding user packages as dependency but i think should be done when we will have also the view.

2021-08-30 07:16 UTC, tibi2303 commented on src/components/bcl-card/card.html.twig
> +      attributes: create_attribute().addClass("mb-3")
Indeed, i added the wrapper.

2021-08-30 07:17 UTC, tibi2303 commented on src/components/bcl-card-layout/__snapshots__/card-layout.test.js.snap
> +
I removed the white spaces and empty lines.

2021-08-30 09:47 UTC, planctus requested changes
It seems pretty much ok to me, please check the comments one by one, but it seems we are close to get this..

2021-08-30 09:47 UTC, planctus commented on src/compositions/bcl-user-listing/user-listing.story.js
> +const scriptInit = (story) => {
mmh..i thought you forgot to add this, but it's not working in the demo...

2021-08-30 09:47 UTC, planctus commented on src/compositions/bcl-user-listing/user-listing.story.js
> +
it's a minor thing, but i don't see the reason why we use "placeholder" as the selected option of the select elements, i think it would be better to try to imagine real use cases and create demos with realistic content, but i understand is an additional overhead (also the "organisation position" thingy in the teasers could be improved). But in any case use one of the existing options, or none, don't add a "placeholder" that is not a placeholder

2021-08-30 09:47 UTC, planctus commented on src/compositions/bcl-user-listing/user-listing.story.js
> +export const Default = () => userListing(correctPaths(demoData));
I think we miss something in the css, i see that you didn't touch it here, but testing a bit the element i noticed that when expanding the viewport from mobile when the offcanvas is visible something bad happens. (i don't know why but i'm unable to attach a screenshot, you should be able to reproduce this easily, though)

2021-08-30 09:47 UTC, planctus commented on src/compositions/bcl-user-listing/package.json
> +  "description": "OE - BCL search",
Update this description text..

2021-08-30 09:47 UTC, planctus commented on src/components/bcl-card/card.html.twig
> +  - category (string) (default: {} - badge object)
this is an array of badge objects, right..? and surely not a string.. :)

2021-08-30 09:51 UTC, planctus commented on src/compositions/bcl-user-listing/package.json
> +  "version": "0.5.0",
I understand, but for the way the subtheme will potentially override these templates it would not work if we have multiple templates in the same package, i'm actually thinking that at the moment it would not be possible to override the offcanvas elements in these two compositions. But yeah, for the moment there is no need.

2021-08-30 11:24 UTC, tibi2303 commented on src/compositions/bcl-user-listing/user-listing.story.js
> +export const Default = () => userListing(correctPaths(demoData));
I added the fix now, but when the offcanvas is opened it's also adding on the body overflow hidden and a padding right.
On this case, it's ok if i override it on the mobile viewport, but i'm thinking of the offcanvas default component which will be impacted by this (we will have the scrollbar when offcanvas is opened on desktop).

2021-08-30 12:15 UTC, planctus commented on src/components/bcl-card/card.html.twig
> +        {% include '@oe-bcl/bcl-badge/badge.html.twig' with _category only %}
Ah wait, i haven't noticed this before, i assumed this was supporting an array of "badges", i mean, why would we limit the "category" to one..? Once we add this let's support multiple badges and maybe, "badges" would also be the right label for this new parameter...

2021-08-30 12:19 UTC, planctus commented on src/compositions/bcl-user-listing/user-listing.html.twig
> +        {% include '@oe-bcl/bcl-select/select.html.twig' with data.sort_select|merge({
not so relevant considering that this is a composition, but still since the themes will ship these templates i would still like to keep them clean, why don't we add these classes in the story (if you don't want to duplicate the elements in the specs)..?

2021-08-30 12:35 UTC, planctus approved these changes

2021-08-30 12:44 UTC, merged