feat(multiselect): Added multiselect accessibility - OEL-2123
openeuropa/bootstrap-component-library pull request #493
Opened 2022-12-08 19:13 UTC by tibi2303

2022-12-09 17:31 UTC, brummbar requested changes
The script added works only on the story, right? It needs to be shipped and activated by users. It probably needs to be in a dedicated JS, so that in Drupal we can include it together with the library.

By the way, what about this option https://slimselectjs.com/settings#allowDeselect ?
It allows to deselect when hovering an entry.

2022-12-12 10:44 UTC, tibi2303 commented on src/components/bcl-select/select.story.js
> +        function setAccesibilty(el, selectedVal) {
I've included your feedback in this new commit - create a new file multiselect.js that it's inside the package.
Also fixed the styles for icons, mobile, error/valid states and fixed a possible bug when multiple multiselect are inside the pages to init all. Please when you can have a look

2022-12-12 10:44 UTC, tibi2303 commented on src/components/bcl-select/select.story.js
> +        function setAccesibilty(el, selectedVal) {
Also this allowDeselect is for removing all items not each one individual.

2023-01-20 14:07 UTC, drishu requested changes
I dont see anything wrong with it per se, but when I integrated it into oe_showcase it made the form completely disappear.
Steps to repro:
- install oe_showcase OEL-1574
- create a project listing page
- override the slimselect.min.js
- override the oe-bcl-default.css
- (adding the multiselect.js is optional, is not relevant to the issue but you can also add it)
- reload the listing page, the form should be gone

2024-11-28 16:11 UTC, closed without merging