feat(gallery): Improved gallery modal captions - OEL-2129
openeuropa/bootstrap-component-library pull request #509
Opened 2023-01-31 15:24 UTC by tibi2303

2023-05-10 17:45 UTC, brummbar requested changes

2023-05-10 17:45 UTC, brummbar commented on src/components/bcl-carousel/carousel.html.twig
> +      caption_visible_mobile (boolean)
Value is never initialised?

2023-05-10 17:45 UTC, brummbar commented on src/compositions/bcl-gallery/data/data.js
> +      caption_visible_mobile: true,
Why should I set this when passing the information about the data?

2023-05-10 17:45 UTC, brummbar commented on src/compositions/bcl-gallery/gallery.html.twig
>                image: ('<iframe' in _item.media or '<img' in _item.media) ? _item.media|replace({'src=': 'data-src='}) : _item.media,
Side note: this breaks if there's another attribute like `<img data-thumbnail-src="...">`.

2023-05-10 17:45 UTC, brummbar commented on src/compositions/bcl-gallery/data/data.js
> +      caption_visible_mobile: true,
This should be rather a parameter of the carousel, possibly marked as internal, which hides the caption on mobile. `show_caption_mobile` or something tied to gallery. Or better, add a block to wrap the needed code and override it when extending the carousel.

2023-05-11 12:41 UTC, tibi2303 commented on src/compositions/bcl-gallery/gallery.html.twig
>                image: ('<iframe' in _item.media or '<img' in _item.media) ? _item.media|replace({'src=': 'data-src='}) : _item.media,
I added an extra space to be sure `src` is as alone without any extra data-. Should be ok i think

2025-02-19 23:31 UTC, closed without merging