feat(multiselect): Fixed overlapping border class. - OEL-2255
openeuropa/bootstrap-component-library pull request #515
Opened 2023-03-08 15:50 UTC by tibi2303

2023-04-05 06:37 UTC, drishu approved these changes

2023-06-27 07:43 UTC, drishu requested changes

2023-06-27 07:43 UTC, drishu commented on src/themes/default/src/scss/_multiselect.scss
> +  border: none;
This didn't work for me but removing the border from ".ss-main .ss-multi-selected" did

2023-07-24 10:32 UTC, tibi2303 commented on src/themes/default/src/scss/_multiselect.scss
> +  border: none;
actually this is mostly reffering to when the .ss-main div has the form-select class which come by default on oe_bootstrap_theme.

2023-11-09 16:15 UTC, brummbar commented
We won't fix this here, but in oe_whitelabel.

2023-11-09 16:15 UTC, closed without merging