ISSUE-#565: Allow client to pass attributes to the pagination list.
openeuropa/bootstrap-component-library pull request #566
Opened 2023-12-15 13:45 UTC by msnassar

2024-08-14 13:11 UTC, drishu approved these changes

2024-08-16 13:08 UTC, brummbar requested changes

2024-08-16 13:08 UTC, brummbar commented on src/components/bcl-pagination/pagination.html.twig
> +  <ul {{ list_attributes }}>
```suggestion
  <ul{{ list_attributes }}>
```

2024-08-16 13:08 UTC, brummbar commented on src/components/bcl-pagination/pagination.html.twig
> +{% endif %}
In Drupal this is done this way
```
set list_classes = [
  size is not empty ? 'pagination-' ~ _size,
  _variant is not empty ? 'pagination--' ~ _variant,
  _alignment is not empty ? 'justify-content-' ~ _alignment,
]
```
Any chance we can use a similar syntax for clarity?

2024-08-19 20:34 UTC, tibi2303 commented on src/components/bcl-pagination/pagination.html.twig
> +{% endif %}
unfortunately this would create empty spaces because of the array not having default values in the params so it would look like this : ['pagination', '', '', ''] and this would create empty spaces inside the class. i wanted to create a filter like in here: https://www.drupal.org/docs/8/modules/twig-tools/sanitization-filters - remove_empty
But again twing... 

Also we have this approach in all templates.. would be a nice to have for later version for sure...

2024-08-21 11:33 UTC, drishu approved these changes

2024-08-21 11:58 UTC, brummbar commented on src/components/bcl-pagination/pagination.html.twig
> +{% endif %}
Ok!

2024-08-21 14:13 UTC, merged