EPHEH-313: Added yml-importer package.
openeuropa/bootstrap-component-library pull request #577
Opened 2024-02-12 16:43 UTC by tibi2303

2024-02-20 08:05 UTC, drishu requested changes
- we need some explanation/documentation on how to use it in a project
- also the way sass is handled by toolkit is through the toolkit:build-assets command which can be set up to use ecl-builder or gulp, after leaving instructions on how to go around this we need to follow up on adding a bcl-builder to it

2024-02-20 08:05 UTC, drishu commented on src/themes/default/src/scss/color_schema.scss
> +@import "@openeuropa/bcl-bootstrap/scss/functions";
the default theme package depends on the bcl bootstrap, can we do something to reflect this in the dependencies section of its package.json? would it break any existing setup?

2024-04-24 14:40 UTC, drishu requested changes

2024-04-24 14:40 UTC, drishu commented on builder/README.md
> +],
Trying to integrate it into oe_showcase I found that this part here is useless

2024-04-24 14:40 UTC, drishu commented on builder/README.md
> +    entry: [path.resolve(nodeModules, "color-scheme.scss")],
```suggestion
    entry: path.resolve(outputFolder, "resources/sass/color-scheme-variables.scss"),
```

2024-04-24 14:40 UTC, drishu commented on builder/README.md
> +    dest: path.resolve(outputFolder, "css"),
```suggestion
    dest: path.resolve(outputFolder, "assets/css/color_scheme.min.css"),
```

2024-04-24 14:40 UTC, drishu commented on builder/README.md
> + color-scheme: [
```suggestion
 colorScheme: [
```

2024-04-24 14:40 UTC, drishu commented on builder/README.md
> +```
Lets explain that this is the contents of the color-scheme-variables.scss

2024-04-24 14:40 UTC, drishu commented on builder/README.md
> +- BCL-Builder version >= 1.2.1
+BCL Bootstrap

But rather let's explain rather what needs to be added into the package, with a minimal setup example (maybe they dont have one yet in their project)

2024-04-24 14:40 UTC, drishu commented on builder/README.md
> +- `scss/color-scheme.scss`: This is the starting imports needed.
useless, remove

Rather mention all that is needed, the package.json, the builder config, variables sass file, node to compile, what commands to run.

2024-04-24 14:40 UTC, drishu commented on builder/scripts/colorScheme.js
> +  console.log(scssContent);
leftover, please remove

2024-04-28 23:07 UTC, tibi2303 commented on builder/README.md
> +```
updated.

2024-04-28 23:07 UTC, tibi2303 commented on builder/README.md
> + color-scheme: [
updated.

2024-04-28 23:07 UTC, tibi2303 commented on builder/README.md
> +    dest: path.resolve(outputFolder, "css"),
updated.

2024-04-28 23:09 UTC, tibi2303 commented on builder/README.md
> +],
removed.

2024-04-28 23:09 UTC, tibi2303 commented on builder/README.md
> +    entry: [path.resolve(nodeModules, "color-scheme.scss")],
updated.

2024-04-28 23:09 UTC, tibi2303 commented on builder/README.md
> +- BCL-Builder version >= 1.2.1
updated.

2024-04-28 23:09 UTC, tibi2303 commented on builder/scripts/colorScheme.js
> +  console.log(scssContent);
removed.

2024-04-28 23:10 UTC, tibi2303 commented on builder/README.md
> +- `scss/color-scheme.scss`: This is the starting imports needed.
Overall i've changed the readme and also provided a basic setup for color schema.

2024-05-03 07:45 UTC, drishu commented on builder/README.md
> +    entry: [path.resolve(nodeModules, "color-scheme.scss")],
not quite, the `"resources/sass/color-scheme-variables.scss"` part is missing

2024-05-03 07:50 UTC, drishu requested changes
Working on the showcase intregration I noticed:

- Carousel does not recipe any color changes
- Gallery receives no color changes
- Timeline circles stay blue

Also one point remains from previous review

2024-05-03 07:50 UTC, drishu commented on builder/scripts/colorScheme.js
> + * ],
you should have updated alo this or remove

2024-05-07 11:37 UTC, tibi2303 commented on builder/scripts/colorScheme.js
> + * ],
I've updated.

Also i fixed the timeline circle and the image banner bottom. The carousel and gallery from my point of view are behaving correctly. I added 2 stories for each of them inside color schema.

2024-05-08 14:37 UTC, drishu approved these changes

2024-06-04 09:13 UTC, tibi2303 commented on src/themes/default/src/scss/color_scheme/_utilities.scss
> +  .bg-#{$color} {
we need also to add text-bg-{#color} utilities

2024-06-04 11:11 UTC, drishu approved these changes

2024-07-24 13:51 UTC, brummbar approved these changes

2024-08-01 13:44 UTC, drishu approved these changes

2024-08-01 13:49 UTC, brummbar approved these changes

2024-08-01 14:01 UTC, merged