EPHEH-313: Color Schema v2.
openeuropa/bootstrap-component-library pull request #581
Opened 2024-02-28 22:11 UTC by tibi2303

2024-03-01 12:14 UTC, drishu requested changes

2024-03-01 12:14 UTC, drishu commented on src/compositions/bcl-color-schema/color-schema.story.js
> +import file from "@openeuropa/bcl-file/file.html.twig";
the icon here is not coloured as in the facts and figures

2024-03-01 12:14 UTC, drishu commented on src/compositions/bcl-color-schema/package.json
> +  "description": "OE - BCL color schema",
not very descriptive

2024-03-01 13:11 UTC, tibi2303 commented on src/compositions/bcl-color-schema/package.json
> +  "description": "OE - BCL color schema",
added description.

2024-03-01 13:12 UTC, tibi2303 commented on src/compositions/bcl-color-schema/color-schema.story.js
> +import file from "@openeuropa/bcl-file/file.html.twig";
indeed, bugs like these may happen, it's hard to forsee all the posibilities.

2024-03-01 13:12 UTC, tibi2303 commented on src/themes/default/src/scss/color-schema.scss
> +    "link": #000dff,
yes, indeed the link color had a problem. Fixed

2024-03-01 13:13 UTC, tibi2303 commented on src/compositions/bcl-color-schema/color-schema.story.js
> +import dataAlert from "@openeuropa/bcl-data-alert/data.js";
Added

2024-03-01 13:25 UTC, tibi2303 commented on src/themes/default/src/scss/color-schema.scss
> +    "text": #fb00ff,
changed the color-schema 😄

2024-03-12 15:06 UTC, drishu requested changes

2024-03-12 15:06 UTC, drishu commented on builder/README.md
> +
I think again to much info

2024-03-12 15:06 UTC, drishu commented on builder/scripts/colorScheme.js
> + *     },
yes, something like this in the readme

2024-03-13 12:36 UTC, tibi2303 commented on builder/scripts/colorScheme.js
> + *     },
added also in readme.

2024-03-13 12:36 UTC, tibi2303 commented on builder/README.md
> +
removed it.

2024-03-13 12:36 UTC, tibi2303 commented on builder/README.md
> +All of these are possible through a namespace class `.{$color-schema-name}`. For example, a banner which uses the color schema will have class `'bcl-banner pixy-pink'`.
removed it.

2024-03-13 12:36 UTC, tibi2303 commented on builder/README.md
> +    entry (string - source file of color-schema),
renamed.

2024-03-13 12:36 UTC, tibi2303 commented on builder/README.md
> +    entry (string - source file of color-schema),
done.

2024-03-13 12:43 UTC, drishu approved these changes

2024-03-15 09:43 UTC, merged