feat(footer): Added composition of footer - Front 3064
openeuropa/bootstrap-component-library pull request #60
Opened 2021-09-14 09:41 UTC by tibi2303

2021-09-14 09:44 UTC, tibi2303 commented on src/themes/default/src/scss/_footer.scss
> +  background: $gray-100;
We will need to sync regarding this variables.. it's not the same background as on figma, also the border color it's different

2021-09-14 10:07 UTC, tibi2303 commented on src/compositions/bcl-footer/footer.story.js
> +                link.icon.path = defaultSprite;
I don't really like this but it may change after we have social content paragraph in place.

2021-09-14 13:49 UTC, planctus commented on src/compositions/bcl-footer/footer.html.twig
> +    ]
wow, try to reduce this comment.. :)

2021-09-14 13:55 UTC, planctus commented on src/compositions/bcl-footer/footer.html.twig
> +<footer class="oe-footer">
i know it's not "final", but let's assume that these templates we make for compositions might be used as such, use drupal attrs on its root element.

2021-09-14 13:59 UTC, planctus commented on src/compositions/bcl-footer/footer.story.js
> +export const Footer = () => footer(correctPaths(footerData));
Really a minor thing, but why not exporting this as `Default` so that you don't have to set its storyName..? :)

2021-09-21 11:32 UTC, tibi2303 commented
The differences between this implementation and links block has some big difference, i decided to keep it as is.

2021-09-27 09:22 UTC, papegaill requested changes
Here are some suggestions for spacings.
I also see EC blue variant on figma, is this requested?

2021-09-27 09:22 UTC, papegaill commented on src/compositions/bcl-footer/footer.html.twig
> +                      {% include '@oe-bcl/bcl-link/link.html.twig' with link|merge({
Not so obvious to validate the spacing next to figma, we must sync with the designers for that. but here I will add an `mb-1` class to give more space between the links (see figma)

2021-09-27 09:22 UTC, papegaill commented on src/compositions/bcl-footer/footer.story.js
> +export const Footer = () => footer(correctPaths(footerData));
is this ok?

2021-09-27 09:22 UTC, papegaill commented on src/data/footer/data.js
> +                    size: "xs",
on these social icons links, I'll put a `me-2` extra_class to give more horizontal space as on figma

2021-09-27 09:23 UTC, papegaill commented on src/data/footer/data.js
> +                "<p class='fw-bold border-bottom pb-2'>Contact [project name]</p>",
not sure, but all the titles seems to have a margin-bottom higher than specified in figma.
maybe a `mb-2` to follow design?

2021-09-27 12:11 UTC, papegaill requested changes

2021-09-27 13:43 UTC, papegaill approved these changes

2021-09-27 13:43 UTC, merged