feat(file): Added download attributes. - OEL-2772
openeuropa/bootstrap-component-library pull request #600
Opened 2024-08-01 13:56 UTC by tibi2303

2024-08-05 16:04 UTC, AaronGilMartinez requested changes

2024-08-06 09:17 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +          attributes: _download.attributes|default(create_attribute().merge(download_attributes))
done, changed the approach as we discussed.

2024-08-06 09:58 UTC, AaronGilMartinez approved these changes

2024-08-07 15:28 UTC, drishu requested changes

2024-08-07 15:28 UTC, drishu commented on src/compositions/bcl-file/file.html.twig
> +          })),
This is too confusing for me, we need to have defaults and merge over what is coming as parameter, so
```
icon: {
              name: "download",
              size: "fluid",
              path: _icon_path,
            }|merge(_download.icon),
```

2024-08-07 15:28 UTC, drishu commented on src/compositions/bcl-file/file.test.js
> +          icon: {
this is the only scenatio with icon, what if I send an empty icon, or one with just the "path"

2024-08-08 09:19 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +        {% set download_attributes = create_attribute()
done.

2024-08-08 09:19 UTC, tibi2303 commented on src/compositions/bcl-file/file.html.twig
> +          })),
indeed, thanks for the improvement, added.

2024-08-08 09:20 UTC, tibi2303 commented on src/compositions/bcl-file/file.test.js
> +          icon: {
added multiple tests, thanks.

2024-08-08 12:17 UTC, drishu approved these changes

2024-08-08 13:30 UTC, AaronGilMartinez approved these changes

2024-08-08 13:47 UTC, merged