Front 3136#default#
openeuropa/bootstrap-component-library pull request #61
Opened 2021-09-14 14:47 UTC by theosuja

2021-09-14 14:50 UTC, tibi2303 commented on src/compositions/bcl-links-block/dataLinksBlock.js
> +  data: {
you don't need to add all specs inside a data object, just keep it in root

2021-09-14 14:53 UTC, tibi2303 commented on src/compositions/bcl-links-block/links-block.html.twig
> +{% set _title = data.title|default('') %}
keep it simple, only title not data.title. same for links

2021-09-14 14:53 UTC, tibi2303 commented on src/compositions/bcl-links-block/links-block.html.twig
> +  - title
more descriptive regarding this (you should use the template from one of the already built component)

2021-09-14 14:53 UTC, tibi2303 commented on src/compositions/bcl-links-block/links-block.story.js
> +export const LinksBlock = () => linksBlock(demoData);
add an end of line here, you should have a setting in visual studio that does this automatically on save

2021-09-14 14:53 UTC, tibi2303 commented on src/compositions/bcl-links-block/links-block.story.js
> +export const LinksBlock = () => linksBlock(demoData);
same goes for most of files

2021-09-14 14:54 UTC, tibi2303 commented
Rename the pr title, to comply with the semantic check, just use one of the already merged pr template title.

2021-09-14 14:57 UTC, tibi2303 commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <p class="fs-5 fw-bold mb-2">{{ _title }}</p>
Here it should be a title object that has 3 props {label: "", classes: "", tag: ""}. You should be able to modify the classes and the tag if you want.

2021-09-14 14:58 UTC, tibi2303 commented on src/compositions/bcl-links-block/links-block.html.twig
> +        <li class="list-unstyled pb-2">
you should add the margin on the link not on the li from my point of view.. add it using drupal_attributes object (addClass('mb-2'))

2021-09-14 14:58 UTC, tibi2303 commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <ul class="ps-0 mb-0">
Here the static classes should come from the data spec not hardcoded

2021-09-14 14:58 UTC, tibi2303 commented on src/compositions/bcl-links-block/links-block.html.twig
> +<div class="bg-light p-3">
Here the static classes should come from the data spec not hardcoded

2021-09-14 14:59 UTC, tibi2303 commented on src/compositions/bcl-links-block/links-block.html.twig
> +<div class="bg-light p-3">
just add {{ attributes }} and from there should be simple enough to add anything you need, not only classes.

2021-09-14 15:56 UTC, theosuja commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <ul class="ps-0 mb-0">
I think these two particular selectors are quite "mandatory" since they override the <ul> reboot. I don't think it makes sense to make them configurable

2021-09-14 16:02 UTC, theosuja commented on src/compositions/bcl-links-block/links-block.html.twig
> +<div class="bg-light p-3">
For now the background isn't going to be optional, it may be in the future or in other compositions. I don't think the padding should be configurable though, any opinion @planctus @papegaill ?
For me it's not superclear yet how is this going to look like once implemented in Drupal, but I feel like this level of configuration is not necessary. Please let me know your thoughts about it.

2021-09-14 16:18 UTC, theosuja commented on src/compositions/bcl-links-block/links-block.html.twig
> +        <li class="list-unstyled pb-2">
100% agreed

2021-09-14 16:25 UTC, theosuja commented on src/compositions/bcl-links-block/links-block.story.js
> +export const LinksBlock = () => linksBlock(demoData);
thanks :)

2021-09-15 09:08 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <ul class="ps-0 mb-0">
Well, i think this approach (including the link) is the same that is currently used in the template used for the "ECL" link-block, but at the same time we already have a bootstrap component handling list of links and i wonder whether the "OEL" design shouldn't be based on that, this is a bootstrap based library in the end..

2021-09-15 10:03 UTC, planctus commented on .storybook/preview.js
> +      order: ['Components', 'Compositions', 'Paragraphs'],
Nice that you "sorted" this Paragraphs thing, but then you placed the example in "compositions" :)

2021-09-15 10:16 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +<div class="bg-light p-3">
Well, the approach we should have is that we offer the possibility via the template to reproduce the design we have, if then we know that one default "variant" has to be set we define this in the template as "default".
In this case it means that:
1) we are using drupal attributes here
2) we add a parameter for the background ( gray, white ), with a default value gray, that you use in to add this class otherwise you add another one for the white bg

padding i agree that might not be a parameter, but you will add it using attributes.addClass()

2021-09-15 10:20 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +{% if title.tag is not empty %}
do we actually need this..? I mean, if in the design we have one style only i don't see why we would give this possibility.
in any case i believe that "title" on drupal means just a string, so in case we need to maintain this configurable it would be better doing it as a different parameter, not making the title an object.

2021-09-15 11:54 UTC, theosuja commented on src/compositions/bcl-links-block/links-block.html.twig
> +{% if title.tag is not empty %}
The first version only had the title as a string, then Tiberiu kindly suggested me to add some options (and I kindly agreed :) ) but in this stage of my life I believe the less configurations are given, the better it is. So if @tibi2303 agrees, it's your decision @planctus

2021-09-15 11:55 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <ul class="ps-0 mb-0">
talked with the designers, let's trick to this implementation that includes link, although i think this is a duplicate of an existing component, basically

2021-09-15 11:56 UTC, planctus commented on src/compositions/bcl-links-block/links-block.story.js
> +  title: "Compositions/Links Block",
Put it in "Paragraphs"

2021-09-15 11:57 UTC, theosuja commented on .storybook/preview.js
> +      order: ['Components', 'Compositions', 'Paragraphs'],
I thought you agreed with @tibi2303 to finally add it here. The commits show that we had it configured as a component in a new section "Paragraphs" but then we moved it back to "Compositions".
I'll ping you to sync on this

2021-09-15 12:00 UTC, tibi2303 commented on src/compositions/bcl-links-block/links-block.html.twig
> +{% if title.tag is not empty %}
sure, well i just proposed from the footer point of view, for me it would have been helpful to have this configurable, you can reverse it :D

2021-09-15 12:13 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +{% if _title_attributes is empty %}
well, we never used title_attributes (drupal) for any component, this would be the first time, but what kind of extra params would we expect for the title..?
I think we don't need this either, basically..

2021-09-15 12:21 UTC, planctus commented on src/compositions/bcl-links-block/links-block.story.js
> +export const LinksBlock = () => linksBlock(demoData);
Once you add the parameter to switch the background you will also have to:
a) create another export for the "other" background
b) add a control named "variant" to make the switch between the two.

Up to you ;)

2021-09-15 13:32 UTC, theosuja commented on src/compositions/bcl-links-block/links-block.html.twig
> +<div class="bg-light p-3">
Would it make sense to use a boolean since we only have 2 possibilities and a default?

2021-09-16 13:16 UTC, tibi2303 commented on src/paragraphs/bcl-links-block/links-block.test.js
> +describe("OE - Links block", () => {
Can you add here a test for horizontal and grey bg? to have a full suite with all cases

2021-09-16 13:24 UTC, tibi2303 commented on src/paragraphs/bcl-links-block/links-block.test.js
> +describe("OE - Links block", () => {
Also did we agreed to move them back to paragraphs? Just asking, if it's the case, after the full test suite it's done, should be ok for me. @planctus if you feel the need to add more, please do :D

2021-09-16 13:39 UTC, planctus commented on package.json
> +      "src/paragraphs/*",
No i see that we made confusion:
in storybook and storybook only we group this into a "paragraphs" labelled thing but there is no need to add another folder in the filesystem with the overhead that you saw, adding this folder here in the package.json, adding the support for the stories, etc..all these things can be reverted and the package should be in src/compositions

2021-09-16 13:56 UTC, planctus commented on src/paragraphs/bcl-links-block/dataLinksBlock.js
> +      path: "#",
we link everything to /example.html, we have an example page for that ;)

2021-09-16 14:01 UTC, planctus commented on src/paragraphs/bcl-links-block/links-block.html.twig
> +{% if list_attributes is empty %}
i don't think we have to use drupal attributes here, i mean this is only an internal processing and you only set classes, isn't it easier to just use a string..?

2021-09-16 14:04 UTC, theosuja commented on src/paragraphs/bcl-links-block/links-block.html.twig
> +{% if list_attributes is empty %}
I am not 100% it's the only way to do it, but I did this to use the logic (l:52) to add classes depending on the variant chosen

2021-09-16 14:20 UTC, theosuja commented on src/paragraphs/bcl-links-block/links-block.html.twig
> +{% if list_attributes is empty %}
indeed the attribute creation can be simplified, but as far as I unerstand it can't be skipped

2021-09-16 14:21 UTC, planctus commented on src/paragraphs/bcl-links-block/links-block.html.twig
> +            attributes: create_attribute().addClass(["pb-2", "d-inline-block"])
The spacing is pretty "approximated", i see that there are values like 20px in the mock and we cannot reproduce that with utilities unless we create additional spacing classes. But this in particular looks a bit evident, it's 16px in the mocks and we make it 8px..i think we should be a bit more precise and if we cannot reproduce exactly what we are asked to we should report that in the figma file and agree with the designers.

2021-09-16 14:23 UTC, planctus commented on src/paragraphs/bcl-links-block/links-block.story.js
> +    variant: data.variant || "gray",
you have only one data file and these two values are available, so why the || in these cases..?

2021-09-16 14:24 UTC, planctus commented on src/paragraphs/bcl-links-block/links-block.story.js
> +      type: { name: "select" },
if it's inline-radio why the type "select", you can remove this or you can replace its value with inline-radio, but simply as type: "inline-radio"

2021-09-16 14:24 UTC, planctus commented on src/paragraphs/bcl-links-block/links-block.story.js
> +      type: { name: "select" },
Also here

2021-09-16 14:29 UTC, planctus commented on src/themes/default/storybook/bcl-builder.config.js
> +      from: ["../../../{components,compositions,paragraphs}/**/*.story.js"],
so this will go away..

2021-09-16 14:30 UTC, planctus commented on src/themes/joinup/storybook/bcl-builder.config.js
> +      `../../../{components,compositions,paragraphs}/**/${story}.story.js`
this also..

2021-09-16 14:30 UTC, planctus commented on src/themes/joinup/storybook/bcl-builder.config.js
> +      from: ["../../../{components,compositions,paragraphs}/**/*.story.js"],
same..

2021-09-16 14:30 UTC, theosuja commented on src/themes/joinup/storybook/bcl-builder.config.js
> +      from: ["../../../{components,compositions,paragraphs}/**/*.story.js"],
yes! those changes are ready to ship

2021-09-16 14:32 UTC, planctus commented on src/paragraphs/bcl-links-block/links-block.html.twig
> +    - options ["vertical", "horizontal"]
but you define white as an accepted value for this parameter but you don't use it, you should set the `bg-white` class if white is the value provided.

2021-09-16 14:34 UTC, theosuja commented on src/paragraphs/bcl-links-block/links-block.html.twig
> +    - options ["vertical", "horizontal"]
indeed

2021-09-16 14:35 UTC, planctus commented on .storybook/environment.js
> +const projParagraphsAbsPath = path.resolve(__dirname, "../src/paragraphs");
this will disappear

2021-09-16 14:35 UTC, planctus commented on .storybook/environment.js
> +  loader.addPath(projParagraphsAbsPath, "oe-bcl");
and then this..

2021-09-16 14:36 UTC, planctus commented on .storybook/main.js
> +const stories = ["../src/{components,compositions,paragraphs}/**/*.story.js"];
this line can be reverted as well

2021-09-16 14:37 UTC, planctus requested changes
A few small thing, it's kind of ok but the "design" compliance is not really high, there are many things not perfectly reproducing the mocks.

2021-09-16 14:45 UTC, theosuja commented on src/paragraphs/bcl-links-block/links-block.story.js
> +    variant: data.variant || "gray",
I must have copied this from another component where it was used

2021-09-16 15:03 UTC, theosuja commented on src/paragraphs/bcl-links-block/links-block.html.twig
> +    <hr/>
that's right

2021-09-16 15:22 UTC, theosuja commented on src/paragraphs/bcl-links-block/links-block.test.js
> +describe("OE - Links block", () => {
thanks @tibi2303 for the support

2021-09-16 15:24 UTC, theosuja commented on src/paragraphs/bcl-links-block/links-block.html.twig
> +    - options ["vertical", "horizontal"]
Now I doubt if it has to be white or transparent actually... i'll ask the designers

2021-09-17 06:17 UTC, theosuja commented
> A few small thing, it's kind of ok but the "design" compliance is not really high, there are many things not perfectly reproducing the mocks.

Pointed the "impossible" values to the designers, once they fix those I'll make sure we are aligned and submit the PR again

2021-09-17 09:35 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <h5 class="fs-5 fw-bold pb-2 border-bottom">{{ _title }}</h5>
Thanks for removing the hr, but what i see here is that you add a 0.5 rem padding bottom (pb-2) and it should be pb-3

2021-09-17 09:36 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <h5 class="fs-5 fw-bold pb-2 border-bottom">{{ _title }}</h5>
and, since you are dealing with the designers about the spacing inconsistencies, would you also ask if the h5 is the right heading from their point of view (mainly a semantical concern)...

2021-09-17 09:37 UTC, theosuja commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <h5 class="fs-5 fw-bold pb-2 border-bottom">{{ _title }}</h5>
![image](https://user-images.githubusercontent.com/45361980/133761640-a8dd511d-3e26-4b9f-b94f-beb76b80fe5e.png)
I assumed that one, but it's better to ask indeed...

2021-09-17 09:40 UTC, theosuja commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <h5 class="fs-5 fw-bold pb-2 border-bottom">{{ _title }}</h5>
It's 12px on the mocks, I had to choose between 8 and 16 so I arbitrarily chose 8. Do you arbitrarily decide that it must be 16?

2021-09-17 09:45 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <h5 class="fs-5 fw-bold pb-2 border-bottom">{{ _title }}</h5>
true, forget it, i thought we had 0.75rem, these spacing utilities are pretty limiting, i think we should extend them in order to have all the 4px steps...

2021-09-17 09:48 UTC, theosuja commented on src/compositions/bcl-links-block/links-block.html.twig
> +    <h5 class="fs-5 fw-bold pb-2 border-bottom">{{ _title }}</h5>
As I told this morning to Julien, I completely agree. We should have some more flexibility on this very specific utility. Who has the authority to decide on this? :)

2021-09-20 11:11 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +          {{ create_attribute().addClass(_list_classes) }}
i think there is really zero value in using drupal attributes here, you can simply work on a string and print it as it is, here we create an object to only store a few classes name with no interaction with drupal, we use drupal attributes for the root of the component and the included templates, so everywhere drupal might be adding his own attrs, not on internal elements, basically...

2021-09-20 11:15 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +            attributes: create_attribute().addClass(["pb-3", "d-inline-block"])
what you should here, instead, is to check whether any "attributes" exists already in the data, if not you create a new one otherwise you just add your classes.

2021-09-20 11:17 UTC, planctus commented on src/themes/default/src/scss/_spacers.scss
> +// scss-docs-start spacer-variables-maps
ok, cool, but Tiberiu is adding a _variables.scss, let's not multiply them, rename this in _variables.scss, we will then merge also the variables from the Tiberiu pr...

2021-09-20 11:18 UTC, planctus commented on src/compositions/bcl-links-block/__snapshots__/links-block.test.js.snap
> +    class=""
why do we have this empty attribute..?

2021-09-20 11:25 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +{% endif %}
can you please ensure that the variant is supposed to be transparent and not white..? Maybe that is the case but since a few things depend on this let's just be sure about it.

2021-09-20 11:26 UTC, planctus commented on src/compositions/bcl-links-block/links-block.story.js
> +      table: {
you should add also a "type" "string" so that it will appear in the "table"

2021-09-20 11:27 UTC, planctus commented on src/compositions/bcl-links-block/links-block.story.js
> +      description: "Direction in which the links are displayed",
you should add also a "type" "string" so that it will appear in the "table"

2021-09-20 11:34 UTC, theosuja commented on src/compositions/bcl-links-block/links-block.html.twig
> +          {{ create_attribute().addClass(_list_classes) }}
fair enough

2021-09-20 11:38 UTC, planctus commented on src/themes/default/src/scss/_spacers.scss
> +// scss-docs-start spacer-variables-maps
please remove also the docs comment, that's from bootstrap..

2021-09-20 15:04 UTC, planctus commented on src/compositions/bcl-links-block/links-block.html.twig
> +        <li class="list-unstyled{% if _direction == "horizontal" %} d-inline{% endif %}{% if loop.last == false %} me-4-5{% endif %}">
i would prefer a cleaner, although more verbose way of setting these classes.
```
{% _list_item_classes = "list_unstyled" %}
{% if _direction == "horizontal" %}
{% set _list_item_classes = _list_item_classes ~ ' d-inline' %}
{% endif %}
{% if loop.last %}
{% set _list_item_classes = _list_item_classes ~ '  me-4-5' %}
{% endif %}
```

2021-09-20 15:31 UTC, merged