OEL-3407: Added focus state on accordion.
openeuropa/bootstrap-component-library pull request #618
Opened 2024-10-23 18:34 UTC by tibi2303

[skip chromatic]

2024-10-28 14:30 UTC, drishu requested changes

2024-10-28 14:30 UTC, drishu commented on src/themes/default/src/scss/_accordion.scss
> +.accordion-button {
as far as I can see the button:focus:not(:focus-visible) from reboot css is preventing this style from being displayed

2024-10-28 22:39 UTC, tibi2303 commented on src/themes/default/src/scss/_accordion.scss
> +.accordion-button {
yes, indeed.. after some investigation we should use :focus-visible.

2024-10-29 08:12 UTC, drishu approved these changes

2024-10-29 08:12 UTC, merged