OEL-3401: Input focus state.
openeuropa/bootstrap-component-library pull request #624
Opened 2024-10-29 12:39 UTC by tibi2303

[skip chromatic]

2024-11-01 12:58 UTC, drishu requested changes

2024-11-01 12:58 UTC, drishu commented on src/themes/default/src/scss/_input.scss
> +    outline: 4px solid $primary;
why is this 4px, might be in figma but dont have access, can you provide screenshot to be clear

2024-11-04 11:11 UTC, tibi2303 commented on src/themes/default/src/scss/_input.scss
> +    outline: 4px solid $primary;
<img width="820" alt="image" src="https://github.com/user-attachments/assets/cb729608-f38b-4a58-ad2a-dd9466f8ab0a">
<img width="820" alt="image" src="https://github.com/user-attachments/assets/159fc8de-d97c-40e5-a565-f71a5ef7e378">

yes, it should be 4px

2024-11-04 11:13 UTC, tibi2303 commented on src/themes/default/src/scss/_input.scss
> +    outline: 4px solid $primary;
also here are the designs for other form elements:
<img width="612" alt="image" src="https://github.com/user-attachments/assets/549b89b0-87a5-4ac6-9163-1805abd9a444">
<img width="612" alt="image" src="https://github.com/user-attachments/assets/e3daf5a3-e908-4233-ab0b-81bb9083715c">
<img width="612" alt="image" src="https://github.com/user-attachments/assets/35651537-0167-4214-b0aa-fe8cfcf38b04">

2024-11-04 15:23 UTC, drishu approved these changes

2024-11-04 15:24 UTC, merged