feat(header) - Added header compositions - Front 3065
openeuropa/bootstrap-component-library pull request #63
Opened 2021-09-16 13:11 UTC by tibi2303

2021-09-17 11:53 UTC, planctus commented on src/themes/default/src/scss/_header.scss
> +.ecl__header .oe-header__project,
I think i'm confused by this naming, i know that we used to have a "default" and an "ecl" like version, that's why ecl was mentioned but now we have two different versions, one for EC and one for EU, both "ecl" based, so i think the rereference to ECL should completely disappear and it can be replaced by EC/EU

2021-09-17 11:55 UTC, planctus commented on src/themes/default/src/scss/_header.scss
> +.oe-header__project,
Also oe is outdated, now we are bcl so if we have to write any new markup this should be prefixed with our "namespace", bcl and not oe anymore

2021-09-17 11:59 UTC, planctus commented on src/compositions/bcl-header/header.html.twig
> +      <p>{{ _project_logo.title }}</p>
And we would wrap the site name in a <p>..? :)
I believe it should be an heading, maybe an <h1>..

2021-09-17 12:07 UTC, planctus commented on src/compositions/bcl-header/header.html.twig
> +    format: {
mmh..well, we know that this might just be a "composition", but at the same time i wouldn't nest the site name into a "logo" kind of parameter, i think you can have `site_name` as one the parameters of the template and separately the logo

2021-09-17 12:10 UTC, planctus commented on src/compositions/bcl-header/header.html.twig
> +  - navbar_settings (Navbar object) (default: {})
mmh..i don't really like this parameter name, wouldn't it be better like simply `topbar` or `head`?

2021-09-17 12:28 UTC, planctus commented on src/themes/default/src/scss/_header.scss
> +.ecl__header .oe-header__project,
Design wise, i've seen in the mocks this area is white for the EU version, not sure you have more up to date info about this

2021-09-17 12:39 UTC, planctus commented on src/themes/default/src/scss/_header.scss
> +  width: 100px;
this 100px is maybe fine for the mobile, but already in tablet it looks very small, maybe that is the breakpoint where it should change size (i know we miss a tablet version in the design, we should probably raise this concern)

2021-09-17 12:41 UTC, planctus commented on src/themes/default/src/scss/_header.scss
>  @media (min-width: 992px) {
shouldn't this be: @include media-breakpoint-up(lg)?

2021-09-17 12:43 UTC, planctus commented on src/themes/default/src/scss/_header.scss
> +.oe-header .notification span {
we need to improve the styles of these links, the color the alignment with the icons, but good that you have found a reasonable way of adding this notification icon.. ;)

2021-09-17 12:45 UTC, planctus requested changes
See the comments, but it seems pretty okish..theo is adding some spacing utilities maybe you will be able to use them to fine tune some of the spacings here..

2021-09-19 20:43 UTC, tibi2303 commented on src/compositions/bcl-header/header.html.twig
> +      <p>{{ _project_logo.title }}</p>
that's how was i added at first but i saw in figma they changed it from heading... not sure, i will ask romain

2021-09-20 06:57 UTC, tibi2303 commented on src/compositions/bcl-header/header.html.twig
> +      <p>{{ _project_logo.title }}</p>
Romain told me that this should be a p or a div, i will let it as a p.

2021-09-20 06:57 UTC, tibi2303 commented on src/themes/default/src/scss/_header.scss
> +.oe-header .notification span {
this improvement will come when we will have the new color variables and spacing.

2021-09-23 08:58 UTC, papegaill requested changes
Really nice !! just a few remarks.
We should also see for the login/language modals, no design for this yet?

2021-09-23 09:02 UTC, papegaill requested changes

2021-09-23 09:02 UTC, papegaill commented on src/data/header/data-ec.js
> +            attributes: new drupalAttribute().addClass([
possible to have the same light focus outline as the button for the search input? we don't see the blue outline on a blue bg: 

<img width="287" alt="Screenshot 2021-09-23 at 10 39 07" src="https://user-images.githubusercontent.com/1289480/134480516-94fe933c-8502-48b8-8d8c-07a95ab5e6a7.png">

2021-09-23 09:02 UTC, papegaill commented on src/themes/default/src/scss/_header.scss
> +  padding-left: 6px;
I'll go for a padding-left of 5px; the number is not correctly center(mac - chrome)
6px:
<img width="62" alt="Screenshot 2021-09-23 at 10 42 22" src="https://user-images.githubusercontent.com/1289480/134478201-16739fc5-0226-479b-98fc-7725e0a16dc0.png">
 
5px:
<img width="72" alt="Screenshot 2021-09-23 at 10 42 00" src="https://user-images.githubusercontent.com/1289480/134478239-e91e50e9-3f3e-4c62-ac3e-eeb68638fb5f.png">
 
Also what if we have more than 1 digit (badge should be extensible):
<img width="64" alt="Screenshot 2021-09-23 at 10 44 31" src="https://user-images.githubusercontent.com/1289480/134478441-99b3cebb-e3b2-48d5-a622-5ebe78c7a687.png">

2021-09-23 09:15 UTC, papegaill commented on src/data/header/data-ec.js
> +            attributes: new drupalAttribute().addClass([
details.. but to me the search icon is not correctly center in the button, she seems to be leaning down :)
I will put a margin-top of -2px on the icon's svg, up to you..

actually:
<img width="263" alt="Screenshot 2021-09-23 at 11 12 41" src="https://user-images.githubusercontent.com/1289480/134482110-9948f874-b936-40c2-9eec-c085fb4a0c8b.png">

with negative top margin: 
<img width="272" alt="Screenshot 2021-09-23 at 11 12 27" src="https://user-images.githubusercontent.com/1289480/134482200-f9e9804b-7bb0-4211-8595-4ccba6ffb960.png">

2021-09-23 13:27 UTC, papegaill requested changes

2021-09-23 13:27 UTC, papegaill commented on src/themes/default/src/scss/_header.scss
> +  bottom: calc(100% - 0.45rem);
`bottom: calc(100% - 0.3rem);` to correctly center the toggle vertically?

2021-09-23 13:27 UTC, papegaill commented on src/themes/default/src/scss/_header.scss
> +  padding-left: 5px;
thank you for the change, but I think the border radius and the position is confusing with 2 digit:

<img width="62" alt="Screenshot 2021-09-23 at 15 15 49" src="https://user-images.githubusercontent.com/1289480/134513952-8c55166f-1f2d-4d72-8a7b-5674aa9663d1.png">

By removing absolute position and use transform, and change border to 10px, here is a better result, I think:

2 digit:
<img width="68" alt="Screenshot 2021-09-23 at 15 16 42" src="https://user-images.githubusercontent.com/1289480/134514103-a738ddde-ab24-4b93-9dd2-2a57a9ea8358.png">

1 digit:
<img width="63" alt="Screenshot 2021-09-23 at 15 16 56" src="https://user-images.githubusercontent.com/1289480/134514175-e9692b6f-a1b4-41f1-8720-bf1d60467800.png">


```
border-radius: 10px;
height: 18px;
line-height: .6rem;
padding-left: 5px;
padding-right: 5px;
transform: translate(-11px, 5px);
z-index: 1;
```

2021-09-23 14:08 UTC, papegaill approved these changes

2021-09-24 09:14 UTC, merged