OEL-3547: Added collapse/expand buttons in accordion.
openeuropa/bootstrap-component-library pull request #632
Opened 2024-12-04 19:26 UTC by tibi2303

[skip chromatic]

2025-01-01 15:12 UTC, drishu requested changes

2025-01-01 15:12 UTC, drishu commented on src/components/bcl-accordion/accordion.html.twig
> +                                    .setAttribute('aria-expanded', open_item ? 'true' : 'false')
think we where doing all these in one go 
```
create_attribute([
..
])
```
everywhere needed pls

2025-01-10 10:49 UTC, tibi2303 commented on src/components/bcl-accordion/accordion.html.twig
> +                                    .setAttribute('aria-expanded', open_item ? 'true' : 'false')
yes, indeed it would be better, but the plugin we use ('twing') for the compiling in js of twig file does not support this format of create_attribute... i know we should use the approach you suggested but in all the twig file we use it like we have it now (with .setAttribute).. maybe a different ticket to investigate and change everywhere to the approach you suggested would be better

2025-01-14 14:17 UTC, drishu requested changes

2025-01-14 14:17 UTC, drishu commented on src/components/bcl-accordion/accordion.html.twig
> +  <div class="accordion-items-wrapper">
I tested and we can drop this

2025-01-14 14:17 UTC, drishu commented on src/components/bcl-accordion/accordion.html.twig
> +  <div class="d-flex justify-content-end gap-3 mb-3">
Can we transfer these to a class?

2025-01-14 14:17 UTC, drishu commented on src/components/bcl-accordion/accordion.html.twig
> +        {% if not _item.stay_open and _expand_button is empty  %}
`and _expand_button is empty` why is this needed?

2025-01-29 21:00 UTC, tibi2303 commented on src/components/bcl-accordion/accordion.html.twig
> +        {% if not _item.stay_open and _expand_button is empty  %}
because this attribute helps the accordion to close other 'tab' when another is opened. And when expand_button is clicked, the behaviour of the accordion does not know how to open all of them, only one because of this attribute. For the collapse_button i dont care, because it only closses all.

2025-01-29 21:01 UTC, tibi2303 commented on src/components/bcl-accordion/accordion.html.twig
> +        {% if not _item.stay_open and _expand_button is empty  %}
when this attribute is not present, all the tabs can be opened separately

2025-01-29 21:19 UTC, tibi2303 commented on src/components/bcl-accordion/accordion.html.twig
> +  <div class="d-flex justify-content-end gap-3 mb-3">
i created an attribute for them.

2025-01-29 21:19 UTC, tibi2303 commented on src/components/bcl-accordion/accordion.html.twig
> +  <div class="accordion-items-wrapper">
deleted.

2025-01-29 21:30 UTC, tibi2303 commented on src/components/bcl-accordion/accordion.html.twig
> +  <div class="accordion-items-wrapper">
this is for the default bootstrap styles
<img width="849" alt="image" src="https://github.com/user-attachments/assets/f11fabde-bd5b-46d6-8b1e-f14be1291cc3" />

on :first-of-type on accordion items it adds a border, when we have the buttons, it no longer adds the border styles because it is not :first-of-type, so i encaspsulate them in a div to have the styles for border

2025-02-11 16:41 UTC, piotrsmykaj approved these changes

2025-02-17 09:34 UTC, drishu reviewed
2 quick on that merge trigger

2025-03-11 14:20 UTC, drishu approved these changes

2025-03-11 14:25 UTC, merged