feat(button-drupal): Refactor button using drupal attributes - FRONT-2371
openeuropa/bootstrap-component-library pull request #7
Opened 2021-07-02 12:17 UTC by tibi2303

2021-07-02 15:09 UTC, planctus requested changes
I'm not super happy about adding new `drupalAttributes()` dozens of times in the specs, but yeah, that's what it has to be and it wouldn't change much if we would do a loop between all these "items" arrays to set it, it would just save a few lines of code..
Anyway, it's pretty ok, there are still a few use cases where you maybe didn't update the code with `create_attribute()` after we added this and some fixes here and there, for the controls you shouldn't be hard most of the times.

2021-07-02 15:24 UTC, tibi2303 commented on src/components/button/button.test.js
> +import drupalAttribute from "drupal-attribute";
because the attributes are kept from the previous iteration of test. i need to reset it somehow, it fails if i delete it.

2021-07-04 18:10 UTC, tibi2303 commented on src/data/alert/data.js
> +const drupalAttribute = require("drupal-attribute");
It's the same as on button tests, the values don't reset, they are kept from the previous tests

2021-07-05 09:07 UTC, tibi2303 commented on src/components/button/button.test.js
> +import drupalAttribute from "drupal-attribute";
I fixed this, I added in twig the case when to create_attribute if none is provided, seems to work now.

2021-07-05 09:07 UTC, tibi2303 commented on src/data/alert/data.js
> +const drupalAttribute = require("drupal-attribute");
I fixed this, I added in twig the case when to create_attribute if none is provided, seems to work now.

2021-07-05 14:05 UTC, tibi2303 commented on src/data/alert/data.js
> +const drupalAttribute = require("drupal-attribute");
Redone this using the new implementation of reset

2021-07-05 14:05 UTC, tibi2303 commented on src/components/button/button.test.js
> +import drupalAttribute from "drupal-attribute";
Redone this using the new implementation of reset

2021-07-06 09:01 UTC, planctus commented on src/components/accordion/accordion.html.twig
> +<div class="{{ _class }}" id="{{ _id }}">
mmhh..i know that we talked about this with francesco and i also know that in html 5 the id that we would set if it's not coming from the data is a valid one, but not in html 4 and we don't control this, so i think it's safer reverting this to what is was before and it makes no difference from the "integration" point of view...

2021-07-06 09:04 UTC, planctus commented on src/components/alert/alert.story.js
> +      defaultValue: data.variant,
would you put it back as it was, @tibi2303, i know that is wrong but it's wrong also like this, and this has been fixed in the builder pull request, so no need to make changes here..

2021-07-06 09:06 UTC, planctus commented on src/components/alert/alert.test.js
> +const render = (params, reset) => renderTwigFileAsNode(template, params, reset);
Also here it seems to me the reset can be passed directly to the renderTwigFileAsNode function as true, no need to alter the render function, i think...

2021-07-06 09:10 UTC, planctus commented on src/components/button/button.html.twig
> +  {% set attributes = attributes.setAttribute('disabled', true).setAttribute('aria-disabled', true) %}
exception, aria-disabled is not a boolean, actually: https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaDisabled

2021-07-06 09:20 UTC, planctus commented on src/components/button/button.story.js
>      ${demo}
i'm not sure the reason why we don't get a warning, the linter conf might be suboptimal, but you are using a function before the definition of it, you should move the resetAttrs above the applyArgs function...

2021-07-06 09:23 UTC, planctus commented on src/components/button/button.story.js
>      ${demo}
and there is a problem, or two still in this stories for the button:

1. if you change the value of the icon size a class is added in the button like `btn btn-s btn-primary btn-l`
2. if you change the icon size the position of the icon is not centered, can we fix this in the icon scss file..?

2021-07-06 09:24 UTC, planctus commented on src/components/accordion/__snapshots__/accordion.test.js.snap
> +          class="accordion-button"
is it normal that we don't have the collapsed class anymore here..?

2021-07-06 09:27 UTC, planctus commented on src/components/button/button.test.js
> +const render = (params, reset) => renderTwigFileAsNode(template, params, reset);
do we need this differentiation between the different tests, couldn't we reset these attributes for all of them and not affecting the render function..?

2021-07-06 09:47 UTC, tibi2303 commented on src/components/accordion/__snapshots__/accordion.test.js.snap
> +          class="accordion-button"
well actually, this the correct version https://getbootstrap.com/docs/5.0/components/accordion/

2021-07-06 10:18 UTC, tibi2303 commented on src/components/button/button.test.js
> +const render = (params, reset) => renderTwigFileAsNode(template, params, reset);
Here we have toggleDemoData and spinnerDemoData which both are adding custom attributes from spec and if we reset all of them, the attributes will be empty.

2021-07-06 10:24 UTC, tibi2303 commented on src/components/button/button.story.js
>      ${demo}
I needed to refactor this part, the size of icon overwrited the size on btn, i change the controls for icons in utils.

2021-07-06 11:31 UTC, planctus commented on src/components/accordion/__snapshots__/accordion.test.js.snap
> +          class="accordion-button"
ok, cool

2021-07-06 11:36 UTC, planctus commented on src/components/button/button.test.js
> +const render = (params, reset) => renderTwigFileAsNode(template, params, reset);
ok

2021-07-06 11:41 UTC, planctus approved these changes

2021-07-06 11:42 UTC, merged