feat(multiselect): Bug fix and large size. - FRONT-3178
openeuropa/bootstrap-component-library pull request #70
Opened 2021-09-21 09:31 UTC by tibi2303

2021-09-27 09:58 UTC, papegaill reviewed
We have small and large sizes, but what about normal size(medium). 
Same as the form input, it seems that this default size is missing, 
or maybe a control issue?

2021-09-27 10:14 UTC, papegaill requested changes
Icon display issue for the large version when no option within the field:
<img width="384" alt="Screenshot 2021-09-27 at 12 11 45" src="https://user-images.githubusercontent.com/1289480/134889797-5a0e7a7e-05f6-4ac0-983a-3884e37c7ca8.png">
<img width="386" alt="Screenshot 2021-09-27 at 12 11 37" src="https://user-images.githubusercontent.com/1289480/134889804-8fde217a-dae6-4d22-ae11-a6cf22149a43.png">
To me icon can be a bit smaller ;)

2021-09-28 14:43 UTC, papegaill commented
> @papegaill I actually found a problem here, we don't actually have the medium size, the normal size of the multiselect is the sm size of the select, so we need to change the default multiselect size to something bigger, and keep the default as the small size.

Thks, can we avoid using `form-control-md` class as it doesn't seems to be part of boostrap? 
https://getbootstrap.com/docs/4.0/components/forms/#sizing
Can we keep same approach as all forms elements?

I also noticed previously that all the form elements on the search page and maybe other ones are on small sizes, not sure this is correct, maybe we will have to change everything to default(medium) sizes, to confirm.. if yes, will ba another ticket.

2021-09-29 08:24 UTC, tibi2303 commented
@papegaill thanks for the remarks, we need to confirm the sizes from search and user pages with the designers, anyway i removed the md size. 👍

2021-09-29 09:47 UTC, planctus commented on src/components/bcl-select/select.html.twig
> +{% if _size is not empty %}
mmh..i believe what we are doing here is going to conflict with what we will need later...the behavior of these form elements in terms of their size is not anymore left to the user choosing a size for it and it should actually be handled via css media queries basing on the viewport.
What has been said is that the size would be "lg" in mobile viewport and "md" in the others as far as i remember

2021-09-29 09:49 UTC, planctus commented on src/themes/default/src/scss/_multiselect.scss
> +  &.form-select-sm {
basically this adaptations should not be based on the class but on a media query, if i'm correct

2021-09-29 09:55 UTC, planctus reviewed
I believe the "styles" are good, but the approach needs probably to be changed basing on this:
https://citnet.tech.ec.europa.eu/CITnet/confluence/display/FRONT/BCL+updates+to+align+on+OEL

2021-09-29 13:53 UTC, tibi2303 commented on src/components/bcl-select/select.html.twig
> +{% if _size is not empty %}
done. hope it's good

2021-09-29 13:53 UTC, tibi2303 commented on src/themes/default/src/scss/_multiselect.scss
> +  &.form-select-sm {
done.

2021-09-30 15:25 UTC, planctus commented
I'm confused, think we do too many things not in the right order, in any case since we are dealing with these sizes for all the form elements i think you can already remove everything related to the size from the template and the story

2021-10-02 10:42 UTC, tibi2303 commented
@planctus I agree, the good order should be : 
1. https://github.com/openeuropa/bootstrap-component-library/pull/81 (sizes) - I already remove the sizes you said in this pr.
2. This pr
3. Search form

2021-10-05 09:01 UTC, planctus approved these changes

2021-10-05 09:02 UTC, merged