feat(search): Added search - FRONT-3177
openeuropa/bootstrap-component-library pull request #72
Opened 2021-09-23 07:44 UTC by tibi2303

2021-09-23 12:03 UTC, tibi2303 commented
I tried to adapt as much as i could to the default form input behaviour, the only problem i have is regarding the floating label, i tried many possible solutions but none works, if you have any idea please.

2021-09-27 12:33 UTC, papegaill commented
> I tried to adapt as much as i could to the default form input behaviour, the only problem i have is regarding the floating label, i tried many possible solutions but none works, if you have any idea please.

for me we can remove the control for the floating label, I don't see the interest for this component to have this option.

2021-09-27 12:52 UTC, papegaill requested changes
Nothing happen with the required control and as mentioned, to me we can remove the floating option/control ;)

2021-09-27 12:52 UTC, papegaill commented on src/components/bcl-form-input/form-input.html.twig
>        {{ attributes }}
input type need to be `search` instead of `text`

2021-09-27 12:52 UTC, papegaill commented on src/components/bcl-form-input/form-input.html.twig
>        {{ attributes }}
to see if we can style the webkit search cancel button: https://stackoverflow.com/questions/22928819/override-the-webkit-search-cancel-button

2021-09-27 13:31 UTC, papegaill commented on src/components/bcl-form-input/form-input.html.twig
>        {{ attributes }}
this should do the trick for styling the search cancel button ;)

```
.bcl-search-bar__input[type="search"]::-webkit-search-cancel-button {
  -webkit-appearance: none;
  height: 16px;
  width: 16px;
  background-image: url("data:image/svg+xml,%3Csvg width='16' height='16' viewBox='0 0 16 16' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M16 8C16 12.4183 12.4183 16 8 16C3.58172 16 0 12.4183 0 8C0 3.58172 3.58172 0 8 0C12.4183 0 16 3.58172 16 8ZM5.35355 4.64645C5.15829 4.45118 4.84171 4.45118 4.64645 4.64645C4.45118 4.84171 4.45118 5.15829 4.64645 5.35355L7.29289 8L4.64645 10.6464C4.45118 10.8417 4.45118 11.1583 4.64645 11.3536C4.84171 11.5488 5.15829 11.5488 5.35355 11.3536L8 8.70711L10.6464 11.3536C10.8417 11.5488 11.1583 11.5488 11.3536 11.3536C11.5488 11.1583 11.5488 10.8417 11.3536 10.6464L8.70711 8L11.3536 5.35355C11.5488 5.15829 11.5488 4.84171 11.3536 4.64645C11.1583 4.45118 10.8417 4.45118 10.6464 4.64645L8 7.29289L5.35355 4.64645Z' fill='%236C757D'/%3E%3C/svg%3E");
  cursor: pointer;
}
```

2021-09-28 10:50 UTC, tibi2303 commented on src/components/bcl-form-input/form-input.html.twig
>        {{ attributes }}
I don't have safari on windows, i pushed the improvements, thanks. Can you please check it if it's working properly?

2021-09-28 14:32 UTC, papegaill commented on src/components/bcl-form-input/form-input.html.twig
>        {{ attributes }}
the type for the input is still `text`

2021-09-29 07:18 UTC, tibi2303 commented on src/components/bcl-form-input/form-input.html.twig
>        {{ attributes }}
done.

2021-09-29 09:30 UTC, planctus commented on src/components/bcl-form-input/form-input.html.twig
> +  - "icon" (icon object) (default: {})
mmh..i don't think this is the way, the icon can be added in the composition i believe, and the form-input can stay as it is,  this is both because this is the only use case we have with an icon and because we also need an additional wrapper, we are making a composition template and that is where these elements should be added.

2021-09-29 09:31 UTC, planctus commented on src/components/bcl-icon/icon.html.twig
> +{% set _wrapper_classes = wrapper_classes|default('') %}
what is this supposed to be used for..?

2021-09-29 09:34 UTC, planctus commented on src/compositions/bcl-search-bar/search-bar.html.twig
> +
It seems to me that for how you made it this could have been done simply with the form template, but if we move here instead the addition of the icon and the wrapper it might make a bit more sense as a composition.

2021-09-29 09:37 UTC, planctus commented on src/compositions/bcl-search-bar/search-bar.story.js
> +const getArgs = (data) => {
We miss the size in the controls and i think it's important

2021-09-29 09:39 UTC, planctus requested changes
In the mocks i see in the second part of the page a different design, i'm not sure what we are supposed to do with that, you probably have more information about this..

2021-09-29 10:51 UTC, tibi2303 commented on src/components/bcl-form-input/form-input.html.twig
> +  - "icon" (icon object) (default: {})
indeed, but at the markup level of the input comes a lot of elements (label, valid/invalid messasge, helper), i need the icon and only the input inside a container because i set the icon with absolute. I know it adds complexity with what we don't really need but i can't find any other way to be able to have all the functionality of the form input that has an icon.

2021-09-29 11:18 UTC, tibi2303 commented
From what i know, the data list is not needed now, we don't have enough info.

2021-09-29 11:23 UTC, tibi2303 commented on src/components/bcl-icon/icon.html.twig
> +{% set _wrapper_classes = wrapper_classes|default('') %}
Forgot about it, done.

2021-09-29 11:23 UTC, tibi2303 commented on src/compositions/bcl-search-bar/search-bar.story.js
> +const getArgs = (data) => {
added for search also.

2021-09-29 13:00 UTC, tibi2303 commented on src/components/bcl-form-input/form-input.html.twig
> +  - "icon" (icon object) (default: {})
done.

2021-09-30 14:36 UTC, planctus commented
In mobile i see this: 
![image](https://user-images.githubusercontent.com/14326885/135476043-c6027894-755a-46d0-9c18-248a26351be5.png)

2021-09-30 14:37 UTC, planctus commented on src/compositions/bcl-search-bar/package.json
> +    "@openeuropa/bcl-form-input": "^0.7.0"
now we need to add also the icon in the dependencies

2021-09-30 14:43 UTC, planctus commented on src/compositions/bcl-search-bar/search-bar.html.twig
> +
i would add also a wrapper where you would render `attributes` but actually i would use also the bcl-search-bar class on it.
In ECL we have a label (for accessibility) but we hide it, i wonder if we shouldn't do the same also here.
Furthermore, shouldn't this composition actually render a "form" tag and it could then maybe renamed as search-form instead of search-bar..?

2021-09-30 15:14 UTC, planctus commented
in the preview i see that the size control is not working properly but it will disappear, so maybe we can just remove it

2021-10-02 10:36 UTC, tibi2303 commented on src/compositions/bcl-search-bar/search-bar.html.twig
> +
The input label already does that, we have it display: none in css, right now you won't have a label displayed on this input.

I added the input_attributes to not overlap with the attributes from the form but still be able to use controls for the story.

The icon is shown correctly on mobile, when we will merge the sizes it will looks good, that's intended.

I also removed the size control for search type but still it will be removed entirely in the sizes pr.

2021-10-04 12:13 UTC, planctus commented on src/compositions/bcl-search-form/search-form.story.js
> +Default.storyName = "Default";
You need to set the storyName only in case its string is different than the name of the exported story. In these two cases it's not needed.

2021-10-04 12:20 UTC, tibi2303 commented on src/compositions/bcl-search-form/search-form.story.js
> +Default.storyName = "Default";
done

2021-10-04 12:27 UTC, planctus commented on src/themes/default/src/scss/_forms.scss
> +    top: 17px;
it looks to me like an "empirical" way of writing css, like this.
The size of the select in mobile is 3rem, the size of the icon is 1rem, so it's value should be (select-size - icon-size) / 2 which is indeed 1rem, 16px vertical, don't get the 17px value, mobile is 11px because (38-16) / 2 makes 11px, but it should be a computed value, not us "hardcoding" it.
Let's try to use rems and not pixels and always use the $spacers map when it's about spacing, more than "hardcoded" values.

2021-10-05 12:10 UTC, planctus commented on src/compositions/bcl-search-form/search-form.html.twig
> +<form
We should also close this tag at some point.. :)

2021-10-05 12:11 UTC, planctus commented on src/compositions/bcl-search-form/search-form.html.twig
> +</div>
but..we don't have a submit button in this form..? :) How is this search going to work..?

2021-10-05 12:11 UTC, tibi2303 commented on src/compositions/bcl-search-form/search-form.html.twig
> +<form
done ...

2021-10-05 12:12 UTC, tibi2303 commented on src/compositions/bcl-search-form/search-form.html.twig
> +</div>
but that's the way it's done in figma, i'm not sure, that's why i added in the beginning as a form input.

2021-10-05 12:35 UTC, planctus commented on src/compositions/bcl-search-form/search-form.html.twig
> +</div>
what do you mean..? in figma there is the way it should look like, then the way it "works" is a matter of the implementation, to me that icon is actually the submit button, indeed.

2021-10-06 06:36 UTC, tibi2303 commented on src/compositions/bcl-search-form/search-form.html.twig
> +</div>
@planctus i refactored the stories and add the mission one. Should be good now. Sorry for all the ping pong on this one.

2021-10-06 12:12 UTC, planctus approved these changes

2021-10-06 12:12 UTC, merged