Front 3175#default#
openeuropa/bootstrap-component-library pull request #74
Opened 2021-09-27 13:20 UTC by theosuja

I have serious doubts if it is worth it to use the card component for this. As I understand, it must be edited to handle one new configuration: row/col classes different than the classic layout ones (not "row" and "col-XX", but others). Mainly because we need the image to have a fixed width/height, not responsive
 
I think the layer of complexity added to handle this simple configuration is not worth it, I believe it would be better to create a new component which would be quite simple and specific.

Please let me know what you think @planctus @tibi2303 

If we decide to continue in this way, the card must be refactored (at least the way we handle horizontal variant and the row/col classes) and the test must be updated. And probably the story so we display this new simple version of the card

2021-09-29 12:30 UTC, planctus requested changes

2021-09-29 12:30 UTC, planctus commented on src/components/bcl-card/card.html.twig
> +      size_auto (boolean)
Are all these changes a leftover since when you tried to use a card..?

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.html.twig
> +{% if attributes is empty %}
mmh..well, i don't necessarily see why shipping this as a "media-object" template, it is true that it might turn to be useful, but i wouldn't consider this "view mode" for the user profile an implementation of a media-object "component" so for me this should be in the "user" series of compositions, bcl-user-something..

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.html.twig
> +  {% set attributes = create_attribute() %}
attributes exists for all the templates in drupal, we never check for their "presence".

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.html.twig
> +  {% set _media_attributes = create_attribute() %}
but why do we have to create a drupal attributes object, can't we simply add those classes coming from the data instead to the class attribute..?

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.html.twig
> +{% set _text_attributes = create_attribute() %}
same here, we use drupal attributes only for the root element and the included templates, because there might be attributes coming from the specs, it's not convenient for us otherwise especially in a simple case like we have here

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.html.twig
> +  <div
i think this classes should be hardcoded here, we are implementing a design, creating a composition, we shouldn't require extra data to be passed, only the "content".

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.html.twig
> +  - text (object) format: {
but why nesting this into an object, i think this could be flattened

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.html.twig
> +  - media (object) format: {
i believe that once renamed in a bcl-user-whatever this parameter could also be renamed to "picture"

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.html.twig
> +      - "extra_classes" (optional) (string) (default: '')
In any case it seems pretty poor in terms of a data structure for this composition, everything goes into a single key of this text object, couldn't we do something better having a "title" or "user_name" and separately an array of items like, i don't know, "roles" where you hardcode in the template the classes you need instead of expecting them from the specs..?

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.html.twig
> +      src="{{ media.path }}"
this is really surprising, we first create a drupal attribute but then we hardcode in the html of the template two attributes..? As i told you here drupal attributes don't make sense so i'm fine with the attributes declared directly in the html, remove the creation of the the drupal attrs and pass also the class as you are doinf with these.

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.story.js
> +import demoDataSmallUser from "@openeuropa/bcl-media-object/dataSmallUser.js";
i don't know why we started going camelCase for these data in the compositions, it's not more than a loose convention, but we normally name these specs data-something-else

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.story.js
> +export const SmallUserView = (args) =>
I think we only need this demo here, but can you set a human readable name for it..?

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-media-object/media-object.story.js
> +  title: "Compositions/Media object",
This will go in the user "folder" in storybook, ok..?

2021-09-29 12:30 UTC, planctus commented on src/compositions/bcl-user-listing/user-listing.html.twig
> +        <h4 class="mb-4">Users ({{ data.cards.length }})</h4>
and how is this related to this work..?

2021-09-29 12:58 UTC, planctus commented
Ah, i don't think this is the expected result in case of "multiple" information, i believe that the image would stay top aligned, can you confirm with the designers..? Also the layout of the "roles" or other information is not clear to me, it might just be as it is right now, one info after the other, but please ensure that instead is not a "column" based layout..

2021-09-29 13:36 UTC, theosuja commented on src/components/bcl-card/card.html.twig
> +      size_auto (boolean)
oh crap, yes they are

2021-09-29 15:43 UTC, theosuja commented on src/compositions/bcl-media-object/media-object.story.js
> +export const SmallUserView = (args) =>
Not sure... you mean the SmallUserView? Anyway it's not relevant anymore

2021-09-29 15:44 UTC, theosuja commented on src/compositions/bcl-media-object/media-object.story.js
> +import demoDataSmallUser from "@openeuropa/bcl-media-object/dataSmallUser.js";
I could be wrong, but I think this is inherited from other components and compositions. I'll try to avoid it

2021-09-30 13:12 UTC, planctus requested changes

2021-09-30 13:12 UTC, planctus commented on src/compositions/bcl-user-listing/user-listing-teaser.html.twig
> +{% spaceless %}
as said previously i don't think we need this

2021-09-30 13:32 UTC, theosuja commented on src/compositions/bcl-user-listing/user-teaser.html.twig
> +  - department (string) (default: '')
indeed, just forgot to update the doc.....

2021-10-01 12:21 UTC, planctus commented on src/compositions/bcl-user-view/user-view-compact.html.twig
> +    <a href="{{ name.link }}" class="fs-5 text-decoration-none mb-0">{{ name.text }}</a>
sorry to point this out only now, but normally when we have a title we don't assume that it has to be a link, i bet that in this case these will be always links but still let's put some logic to alternatively render simply the "text" if the "link" is empty.

2021-10-01 12:56 UTC, planctus requested changes

2021-10-01 12:56 UTC, planctus commented on src/compositions/bcl-user-view/user-view-compact.story.js
> +import demoDataCompact from "@openeuropa/bcl-user-view/dataUserViewCompact.js";
there is no reason why you had to create a different story file, add this story to the existing one.

2021-10-01 12:56 UTC, planctus commented on src/compositions/bcl-user-view/user-view-compact.story.js
> +  title: "Compositions/Users/View",
This is also explaining the reason why you don't have padding around your component, the default story of user-view is setting the layout to fullscreen, you are duplicating here the same "title" so you basically inherit that setting. When you will move it into the user-view.story.js you will have to override in the Compact.parameters object.

2021-10-04 11:22 UTC, planctus approved these changes

2021-10-04 11:22 UTC, planctus approved these changes

2021-10-04 11:24 UTC, merged